### ISSUE TITLE
REST-Service API-Layer - OptionalInt reise PersistenceException

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#100]
I save the following class into Microstream and startet Api Server. Then i want to see this data via GUI and i Received 500 Error. 

class:
```
    static class OptionalIntData {
        OptionalInt value = OptionalInt.of(0);
        public void fillSampleData() {
            value = OptionalInt.of(44356);
        }
    }
```

Server callstack:
```
one.microstream.persistence.exceptions.PersistenceException: Inconsistent state for instance java.util.OptionalInt@307fdbe3: "44356" not equal to "11355137"
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.throwInconsistentStateException(AbstractBinaryHandlerCustomValue.java:77)
	at one.microstream.java.util.BinaryHandlerOptionalInt.validateState(BinaryHandlerOptionalInt.java:134)
	at one.microstream.java.util.BinaryHandlerOptionalInt.validateState(BinaryHandlerOptionalInt.java:1)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.updateState(AbstractBinaryHandlerCustomValue.java:86)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.updateState(AbstractBinaryHandlerCustomValue.java:1)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerBasic.updateState(ViewerBinaryTypeHandlerBasic.java:36)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerWrapperAbstract.updateState(ViewerBinaryTypeHandlerWrapperAbstract.java:1)
	at one.microstream.persistence.types.PersistenceTypeHandler.initializeState(PersistenceTypeHandler.java:46)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.buildInstances(BinaryLoader.java:449)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.build(BinaryLoader.java:388)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:824)
	at one.microstream.storage.restadapter.ViewerBinaryPersistenceManager.getStorageObject(ViewerBinaryPersistenceManager.java:216)
	at one.microstream.storage.restadapter.EmbeddedStorageRestAdapter.getStorageObject(EmbeddedStorageRestAdapter.java:56)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReference(ObjectDescription.java:190)
	at one.microstream.storage.restadapter.ObjectDescription.lambda$2(ObjectDescription.java:149)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReferences(ObjectDescription.java:150)
	at one.microstream.storage.restadapter.StorageRestAdapter$Default.getObject(StorageRestAdapter.java:72)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:36)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:1)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

```

The same problem for OptionalLong
```
[qtp1365828331-22] ERROR spark.http.matching.GeneralError - 
one.microstream.persistence.exceptions.PersistenceException: Inconsistent state for instance java.util.OptionalLong@1c539aed: "44356" not equal to "11355137"
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.throwInconsistentStateException(AbstractBinaryHandlerCustomValue.java:77)
	at one.microstream.java.util.BinaryHandlerOptionalLong.validateState(BinaryHandlerOptionalLong.java:121)
	at one.microstream.java.util.BinaryHandlerOptionalLong.validateState(BinaryHandlerOptionalLong.java:1)
...
```

**Comment by zdenek-jonas** [comment]
Ok
