### ISSUE TITLE
java.lang.management.ManagementFactory - not in Android API, Lazy cannot be used

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#111]
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryUsage;

are not api on Android, so we cannot use the Lazy on Android. 

```
E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/EGL_emulation: eglMakeCurrent: 0xebe05360: ver 2 0 (tinfo 0xebe03440)
E/AndroidRuntime: FATAL EXCEPTION: LazyReferenceManager@256438757
    Process: one.microstream.android, PID: 14040
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
        at one.microstream.reference.Lazy$Checker$Default.updateMemoryUsage(Lazy.java:740)
        at one.microstream.reference.Lazy$Checker$Default.beginCheckCycle(Lazy.java:723)
        at one.microstream.reference.LazyReferenceManager$Default.internalCleanUp(LazyReferenceManager.java:367)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUp(LazyReferenceManager.java:465)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUpBudgeted(LazyReferenceManager.java:417)
        at one.microstream.reference.LazyReferenceManager$Default$LazyReferenceCleanupThread.run(LazyReferenceManager.java:639)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/one.microstream.android-yV0YrGFow_Z8INYPmQnGtA==/base.apk"],nativeLibraryDirectories=[/data/app/one.microstream.android-yV0YrGFow_Z8INYPmQnGtA==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at one.microstream.reference.Lazy$Checker$Default.updateMemoryUsage(Lazy.java:740) 
        at one.microstream.reference.Lazy$Checker$Default.beginCheckCycle(Lazy.java:723) 
        at one.microstream.reference.LazyReferenceManager$Default.internalCleanUp(LazyReferenceManager.java:367) 
        at one.microstream.reference.LazyReferenceManager$Default.cleanUp(LazyReferenceManager.java:465) 
        at one.microstream.reference.LazyReferenceManager$Default.cleanUpBudgeted(LazyReferenceManager.java:417) 
        at one.microstream.reference.LazyReferenceManager$Default$LazyReferenceCleanupThread.run(LazyReferenceManager.java:639) 
```

**Comment by tm-ms** [comment]
`GoldfishAddressSpaceHostMemoryAllocator`
...
:-D

Anyway:
That is part of the LazyReferenceManager. Lazy references would theoretically function without it.
To solve this, we need to modularize the memory providing logic so that it can be switched out for something android compatible.
Coding wise, this is relatively simple, but it will complicate the project management and deployment a lot, I guess.

**Comment by tm-ms** [comment]
I took a look into the code and there already is a modular `MemoryStatistics` interface and a modular `MemoryStatisticsProvider` interface, with the default implementation using the Oracle Java API.

So all that is required is to implement those two trivial types with android-specific code and switch the static provider on android.

The question is how to structure this in the code projects and in deployment.

**Comment by tm-ms** [comment]
This plus there probably will have to be dependencies to android-specific API to access the memory querying features. Or we'd have to code everything in reflection plain strings ...

**Comment by zdenek-jonas** [comment]
fix with commit:
https://bitbucket.org/microstreamone/microstream/commits/6fe637a9fd8cd7cdfc22de1c4d2ef2633eadd487
