### ISSUE TITLE
EmbeddedStorageRestAdapter does not recognize new Types

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#116]
This issue has been observed by CK.

Howto:

1. Create a new storage with an enabled rest service
2. Store some **custom** objects into the running storage
3. Connect with rest viewer ui or an other rest viewer tool to the restservice
4. Try to navigate to the newly added objects
=> the storage service will throw an exception:

one.microstream.persistence.exceptions.PersistenceExceptionTypeHandlerConsistencyUnhandledTypeId: No type handler found for type id "1000067".
	at one.microstream.persistence.binary.types.BinaryLoader$Default.lookupTypeHandler(BinaryLoader.java:190)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:198)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:154)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:142)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:266)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:275)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:801)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:771)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:839)
	at one.microstream.storage.restadapter.ViewerBinaryPersistenceManager$Default.getStorageObject(ViewerBinaryPersistenceManager.java:291)
	at one.microstream.storage.restadapter.EmbeddedStorageRestAdapter$Default.getStorageObject(EmbeddedStorageRestAdapter.java:89)
	at one.microstream.storage.restadapter.StorageRestAdapter$Default.getObject(StorageRestAdapter.java:94)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:36)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:1)

5. After an restart of the storage the exceptions does no more occur

**Comment by hg-ms** [comment]
related to forum: https://microstream.one/support/forum/topic/71/page/1/

**Comment by hg-ms** [comment]
This is caused because the ViewerBinaryTypeHandlerManager creates type handlers for the viewer only in its constructor. If the storage stores new types after the ViewerBinaryTypeHandlerManager has been constructed it won’t find a “viewer” – type handler for that type.

The solution is quite simple. If no “viewer” handler is found create and register a new one in ViewerBinaryTypeHandlerManager#lookupTypeHandler(long)

**Comment by hg-ms** [comment]
bug fixed with commit 593c2eaed1eb5d13c20c7c45be1aa61c442e0b46 "fixed bug microstream-one/microstream-private#294: EmbeddedStorageRestAdapter does not recognize new Types"

**Comment by zdenek-jonas** [comment]
Ok, tested, works. 
New GUI acceptance test in Selenium written, to test this behaviour automatically.
