### ISSUE TITLE
Communication: Send unsupported Type raise not Meaningful Exception 

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#123]
When i send a Throwable or WeakReference, i expect some Exception, which tells me, that i send an unsupported  type. Instead of i received:

```
Caused by: java.lang.ClassCastException: one.microstream.com.binarydynamic.ComMessageData cannot be cast to one.microstream.com.binarydynamic.ComMessageStatus
	at one.microstream.com.binarydynamic.ComHandlerSendMessageNewType.sendMessage(ComHandlerSendMessageNewType.java:34)
	at one.microstream.com.binarydynamic.ComHandlerSendMessageNewType.sendMessage(ComHandlerSendMessageNewType.java:48)
	at one.microstream.com.binarydynamic.ComChannelDynamic.send(ComChannelDynamic.java:59)
	at one.microstream.com.binarydynamic.ComTypeDescriptionRegistrationObserver.observeTypeDefinitionRegistration(ComTypeDescriptionRegistrationObserver.java:34)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.synchRegisterType(PersistenceTypeDictionary.java:303)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.registerTypeDefinition(PersistenceTypeDictionary.java:356)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.registerRuntimeTypeDefinition(PersistenceTypeDictionary.java:393)
...
```
which really doesn't help me to understand what is wrong.

**Comment by hg-ms** [comment]
No more reproduceable, tested code was not final.
