### ISSUE TITLE
Communication: Add application protocol to prevent data misuse

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#124]
Currently, all security is performed at the transport layer level. Which is good protection against attack man in the middle. However, this protection fails completely when the end node is compromised or in the event of an error in the client node.
We should add at least some format for data messages so that in the case of sending some random bytes, no attempt will be made on the server side to process them.
For example, add a header, a checksum, and a protocol version.

Why:
Just now i can connect to server e.g. with following commands:
`openssl s_client -connect 192.168.1.114:1099 -state -debug -key example.key -cert example.crt` 
If I have the correct certificate, the server will immediately send me the complete type dictionary.
What's worse, I'm able to send anything from the server client now, such as the text "OK"
The server performs absolutely no validation and directly tries to process such a message. This could lead to microstream data corruption, for example in the event of an error of client.

```
Exception in thread "main" one.microstream.com.ComException
	at one.microstream.com.ComChannelExceptionHandler.defaultHandleException(ComChannelExceptionHandler.java:18)
	at one.microstream.com.ComChannelExceptionHandler$Default.handleException(ComChannelExceptionHandler.java:46)
	at one.microstream.com.ComConnectionAcceptor$Default.acceptConnection(ComConnectionAcceptor.java:111)
	at one.microstream.com.ComHost$Default.synchAcceptConnection(ComHost.java:165)
	at one.microstream.com.ComHost$Default.acceptConnections(ComHost.java:147)
	at one.microstream.com.ComHost$Default.run(ComHost.java:113)
	at one.microstream.com.binarydynamic.test.MainTestComTLSServerDynamic.main(MainTestComTLSServerDynamic.java:48)
Caused by: one.microstream.exceptions.ArrayCapacityException: Java technical array capacity limit of max signed 32 bit integer value exceeded: 3544907067364617521
	at one.microstream.X.checkArrayRange(X.java:135)
	at one.microstream.com.binary.ComBinary.readChunk(ComBinary.java:119)
	at one.microstream.com.binary.ComPersistenceChannelBinary$Default.internalRead(ComPersistenceChannelBinary.java:142)
	at one.microstream.com.binary.ComPersistenceChannelBinary$Default.internalRead(ComPersistenceChannelBinary.java:1)
	at one.microstream.com.ComPersistenceChannel$Abstract.read(ComPersistenceChannel.java:52)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOnce(BinaryLoader.java:707)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:824)
	at one.microstream.persistence.types.PersistenceManager$Default.get(PersistenceManager.java:379)
	at one.microstream.com.binarydynamic.ComChannelDynamic.requestUnhandled(ComChannelDynamic.java:44)
	at one.microstream.com.binarydynamic.ComHandlerSendMessageNewType.sendMessage(ComHandlerSendMessageNewType.java:34)
	at one.microstream.com.binarydynamic.ComHandlerSendMessageNewType.sendMessage(ComHandlerSendMessageNewType.java:48)
	at one.microstream.com.binarydynamic.ComChannelDynamic.send(ComChannelDynamic.java:59)
	at one.microstream.com.binarydynamic.ComTypeDescriptionRegistrationObserver.observeTypeDefinitionRegistration(ComTypeDescriptionRegistrationObserver.java:34)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.synchRegisterType(PersistenceTypeDictionary.java:303)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.registerTypeDefinition(PersistenceTypeDictionary.java:356)
	at one.microstream.persistence.types.PersistenceTypeDictionary$Default.registerRuntimeTypeDefinition(PersistenceTypeDictionary.java:393)
	at one.microstream.persistence.types.PersistenceTypeDictionaryManager$Abstract.registerRuntimeTypeDefinition(PersistenceTypeDictionaryManager.java:134)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.synchUnvalidatedRegisterTypeHandler(PersistenceTypeHandlerManager.java:639)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandler(PersistenceTypeHandlerManager.java:608)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.internalEnsureTypeHandler(PersistenceTypeHandlerManager.java:588)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:357)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:333)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.registerGuaranteed(BinaryStorer.java:557)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.registerLazyOptional(BinaryStorer.java:572)
	at one.microstream.persistence.types.PersistenceObjectManager$Default.ensureObjectId(PersistenceObjectManager.java:182)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.register(BinaryStorer.java:591)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.apply(BinaryStorer.java:298)
	at one.microstream.persistence.binary.types.BinaryValueFunctions$17.storeValueFromMemory(BinaryValueFunctions.java:296)
	at one.microstream.persistence.binary.types.Binary.storeFixedSize(Binary.java:1149)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.store(AbstractBinaryHandlerReflective.java:497)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.store(AbstractBinaryHandlerReflective.java:1)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.storeItem(BinaryStorer.java:414)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.storeGraph(BinaryStorer.java:403)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.store(BinaryStorer.java:421)
	at one.microstream.persistence.types.PersistenceManager$Default.store(PersistenceManager.java:274)
	at one.microstream.com.binarydynamic.ComChannelDynamic.send(ComChannelDynamic.java:63)
	at one.microstream.com.binarydynamic.test.MainTestComTLSServerDynamic.lambda$0(MainTestComTLSServerDynamic.java:37)
	at one.microstream.com.ComConnectionAcceptor$Default.acceptConnection(ComConnectionAcceptor.java:107)
	... 4 more
```

**Comment by hg-ms** [comment]
This scenario is no more applicable. Connecting with Openssl is no more possible. Additionally, the server will close the connection if not processable data is received.
