### ISSUE TITLE
AFS/AWS/DynamoDB - NPE DynamoDbConnector.java:105

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#131]
When i run offical Amazon DynamoDB mock database docker image
`docker run -p 8000:8000 amazon/dynamodb-local` 

And run following code:
```
package one.microstream.afs.aws.dynamodb;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;

import com.amazonaws.services.s3.model.Region;
import one.microstream.afs.blobstore.BlobStoreFileSystem;
import one.microstream.afs.blobstore.BlobStoreFileSystemTest;

public class DynamoDbFileSystemTest extends BlobStoreFileSystemTest
{
	
	@Override
	protected BlobStoreFileSystem setupFileSystem()
	{
		final BasicAWSCredentials credentials = new BasicAWSCredentials(
			"accessKey",
			"secretKey");

		final AmazonDynamoDB      client      = AmazonDynamoDBClientBuilder.standard()
			.withCredentials(new AWSStaticCredentialsProvider(credentials))
				.withEndpointConfiguration(
						new AwsClientBuilder.EndpointConfiguration(
								"http://localhost:8000/",
								Region.EU_Frankfurt.getFirstRegionId()
						)
				)
			.build();
		
		return BlobStoreFileSystem.New(
			DynamoDbConnector.New(client)
		);
	}
	
	@Override
	protected void cleanupFileSystem()
	{
	}

}

```

I received NPE for truncateTest()
```
java.lang.NullPointerException
	at one.microstream.afs.aws.dynamodb.DynamoDbConnector$Default.lambda$1(DynamoDbConnector.java:105)
	at one.microstream.afs.blobstore.BlobStoreConnector$Abstract.internalTruncateFile(BlobStoreConnector.java:353)
	at one.microstream.afs.blobstore.BlobStoreConnector$Abstract.truncateFile(BlobStoreConnector.java:658)
	at one.microstream.afs.blobstore.BlobStoreIoHandler$Default.specificTruncateFile(BlobStoreIoHandler.java:412)
	at one.microstream.afs.blobstore.BlobStoreIoHandler$Default.specificTruncateFile(BlobStoreIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.truncate(AIoHandler.java:757)
	at one.microstream.afs.AWritableFile.truncate(AWritableFile.java:96)
	at one.microstream.afs.AbstractFileSystemTest.truncateTest(AbstractFileSystemTest.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```

![image](https://user-images.githubusercontent.com/17253582/87286000-8cb7a300-c4f8-11ea-9342-aa5e3183b0db.png)

**Comment by zdenek-jonas** [comment]
Ok
