### ISSUE TITLE
AFS/NIO  java.nio.channels.NonReadableChannelException

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#133]
During test: NioFileSystemTest
Project: microstream-test
Branch: AFS
Path: Microstream-test/afs/mio/src/test/....

exception:
```
java.nio.channels.NonReadableChannelException
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:714)
	at one.microstream.io.XIO.internalRead(XIO.java:1136)
	at one.microstream.io.XIO.read(XIO.java:1105)
	at one.microstream.io.XIO.read(XIO.java:1072)
	at one.microstream.io.XIO.read(XIO.java:1059)
	at one.microstream.io.XIO.read(XIO.java:1050)
	at one.microstream.afs.nio.NioIoHandler$Default.specificReadBytes(NioIoHandler.java:193)
	at one.microstream.afs.nio.NioIoHandler$Default.specificReadBytes(NioIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.readBytes(AIoHandler.java:498)
	at one.microstream.afs.AReadableFile.readBytes(AReadableFile.java:59)
```
![image](https://user-images.githubusercontent.com/17253582/87418209-99f49080-c5d1-11ea-82bb-1bab6ad9bc11.png)

source code:
```
package one.microstream.afs.nio;

import one.microstream.afs.AbstractFileSystemTest;

public class NioFileSystemTest extends AbstractFileSystemTest<NioFileSystem>
{
	@Override
	protected NioFileSystem setupFileSystem()
	{
		return NioFileSystem.New();
	}
	
	@Override
	protected void cleanupFileSystem()
	{
	}
	
}
```

**Comment by zdenek-jonas** [comment]
Ok, this problem is fixed.
