### ISSUE TITLE
AFS/NIO - NoSuchfileException - downgrade Test

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#136]
In this test, a file is initially created. However, this file is not created. Bug?

project: microstream-test
branch: afs

test location: afs/nio/.... NioFileSystemTest

```

one.microstream.exceptions.IORuntimeException: java.nio.file.NoSuchFileException: microstream_afs_test_1/test_dir/test_subdir/test.dat

	at one.microstream.afs.nio.NioFileWrapper$Abstract.openChannel(NioFileWrapper.java:210)
	at one.microstream.afs.nio.NioFileWrapper$Abstract.ensureOpenChannel(NioFileWrapper.java:153)
	at one.microstream.afs.nio.NioFileSystem$Default.convertToReading(NioFileSystem.java:236)
	at one.microstream.afs.AccessManager$Default.convertToReading(AccessManager.java:509)
	at one.microstream.afs.AccessManager$Default.downgrade(AccessManager.java:556)
	at one.microstream.afs.AWritableFile.downgrade(AWritableFile.java:109)
	at one.microstream.afs.AbstractFileSystemTest.downgradeTest(AbstractFileSystemTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```

Test:
```
	@Test
	@Order(4)
	void downgradeTest()
	{
		final AFile         file  = this.fileSystem.ensureFilePath(this.filePath1);
		final AReadableFile rFile = file.useWriting().downgrade();
		
		assertThrows(Exception.class, () -> file.useWriting("Other user 2"));
		assertDoesNotThrow(() -> file.useReading("Other user 2").release());
		
		rFile.release();
	}
```

Test init:
```
package one.microstream.afs.nio;

import one.microstream.afs.AbstractFileSystemTest;

public class NioFileSystemTest extends AbstractFileSystemTest<NioFileSystem>
{
	@Override
	protected NioFileSystem setupFileSystem()
	{
		return NioFileSystem.New();
	}
	
	@Override
	protected void cleanupFileSystem()
	{
	}
	
}
```

**Comment by tm-ms** [comment]
I found and fixed a tiny but fatal bug in AFS code.
But I can't test it because the test project references a different branch.
To add some confusion to that, there are some kind of library source inconsistencies in my microstream-test project locally.

**Comment by zdenek-jonas** [comment]
Diese Bug ist gefixt
