### ISSUE TITLE
Configuration: Create backup in folder with config endet with java.lang.RuntimeException: Incompatible parent FileSystem ...

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#140]
The test tested configuration via ini files. 

```
class BackupDirectoryTest {

    @TempDir
    Path location;

    Path configFilePath;

    @Test
    void backupDirectoryTest() throws IOException, InterruptedException {
        configFilePath = location.resolve("backupDirectory.ini");

        Path backupLocation = location.resolve("backup");

        FileUtils.writeStringToFile(configFilePath.toFile(),"backupDirectory = "+ backupLocation.toString(), "UTF-8");

        List<Customer> customers = new ArrayList<>();
        customers.add(CustomerGenerator.generateNewCustomer());

        Configuration configuration = Configuration.LoadIni(configFilePath.toUri().toURL());

        EmbeddedStorageManager storageManager = configuration.setBaseDirectory(location.toString()).createEmbeddedStorageFoundation().createEmbeddedStorageManager(customers).start();

        Thread.sleep(1000);

        List<File> files = (List<File>) FileUtils.listFiles(backupLocation.toFile(), null, true);

        assertTrue(files.size() > 2, files.toString());

        storageManager.shutdown();
    }

```

After launch reise an Exception: 
```
java.lang.RuntimeException: Incompatible parent FileSystem of one.microstream.afs.ADirectory$Default@5f481b73:one.microstream.afs.nio.NioFileSystem$Default@32130e61 != this (one.microstream.afs.nio.NioFileSystem$Default@41294371).

	at one.microstream.afs.AFileSystem$Abstract.validateMember(AFileSystem.java:242)
	at one.microstream.storage.types.StorageFileProvider$Builder$Abstract.setDirectory(StorageFileProvider.java:127)
	at one.microstream.storage.types.StorageFileProvider$Builder$Abstract.setDirectory(StorageFileProvider.java:1)
	at one.microstream.storage.configuration.EmbeddedStorageFoundationCreator$Default.createFileProvider(EmbeddedStorageFoundationCreator.java:87)
	at one.microstream.storage.configuration.EmbeddedStorageFoundationCreator$Default.createFoundation(EmbeddedStorageFoundationCreator.java:51)
	at one.microstream.storage.configuration.Configuration.createEmbeddedStorageFoundation(Configuration.java:591)
...
```

Project: microstream-test
branch: master
Test location: microstream-test/intern/src/main/test/java/test.microstream/configuration/BackupDirectoryTest.java

**Comment by fh-ms** [comment]
StorageFileProvider created new NioFileSystem, now uses the singleton which fixes the described issue.
Test still fails, but now with same exception like in microstream-one/microstream-public#139

**Comment by zdenek-jonas** [comment]
Ok this problem is fixed, the another is still there.
