### ISSUE TITLE
NPE in shutdown on a not yet started EmbeddedStorageManager

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#145]
If an EmbeddedStorageManager instance is created without starting it an NullPointerException is thrown if shutdow() is called:

```
public class ExceptionOnShutdown
{
	public static void main(final String[] args)
	{
		final EmbeddedStorageManager embeddedStorageManager = EmbeddedStorage.Foundation().createEmbeddedStorageManager();
	
		embeddedStorageManager.shutdown();
	}
}

```

```
Exception in thread "main" java.lang.NullPointerException
	at one.microstream.storage.types.StorageSystem$Default.internalShutdown(StorageSystem.java:466)
	at one.microstream.storage.types.StorageSystem$Default.shutdown(StorageSystem.java:553)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.shutdown(EmbeddedStorageManager.java:347)
	at one.tests.ExceptionOnShutdown.main(ExceptionOnShutdown.java:12)
```

**Comment by tm-ms** [comment]
The cause for this was that the taskbroker instance used to create the shutdown task is not created before starting.
I added a synchronized null check so such a no-op shutdown call won't crash anymore.

**Comment by hg-ms** [comment]
Looks good, all those NPEs i observed during the microstream-spring-starter configuration tests are gone.
