### ISSUE TITLE
SQL Oracle - java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#146]
SQL Oracle test failed:

branch microstream: feature/FH_priv308_IO-Layer_Implementations
branch microstream-test: afs
test path: microstream-test/afs/sql-oracle/test/java/one/microstream/afs/sql/OracleSqlFileSystemTest

docker command:
`docker run -p 1521:1521 repo.microstream.one:18081/oracle-xe:18c`

```
java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

	at one.microstream.afs.sql.SqlProvider$Abstract.execute(SqlProvider.java:309)
	at one.microstream.afs.sql.SqlConnector$Default.fileExists(SqlConnector.java:584)
	at one.microstream.afs.sql.SqlIoHandler$Default.subjectFileExists(SqlIoHandler.java:96)
	at one.microstream.afs.sql.SqlIoHandler$Default.specificExists(SqlIoHandler.java:120)
	at one.microstream.afs.sql.SqlIoHandler$Default.specificExists(SqlIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.exists(AIoHandler.java:483)
	at one.microstream.afs.AIoHandler$Abstract.ensureExists(AIoHandler.java:630)
	at one.microstream.afs.AWritableFile.ensureExists(AWritableFile.java:89)
	at one.microstream.afs.AbstractFileSystemTest.writeTest(AbstractFileSystemTest.java:208)
...
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3713)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1167)
	at one.microstream.afs.sql.SqlConnector$Default.queryFileExists(SqlConnector.java:109)
	at one.microstream.afs.sql.SqlConnector$Default.lambda$7(SqlConnector.java:585)
	at one.microstream.afs.sql.SqlProvider$Abstract.execute(SqlProvider.java:304)
	... 71 more
Caused by: Error : 942, Position : 21, Sql = select count(*) from "microstream_afs_test_1_test_dir_test_subdir" where "identifier"=:1 , OriginalSql = select count(*) from "microstream_afs_test_1_test_dir_test_subdir" where "identifier"=?, Error Msg = ORA-00942: table or view does not exist
```

**Comment by zdenek-jonas** [comment]
This problem affects all databases

**Comment by zdenek-jonas** [comment]
ok works
