### ISSUE TITLE
Backup directory test - Incompatible parent FileSystem of ...

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#147]
I have following test:

```
class BackupDirectoryTest {

    @TempDir
    Path location;

    Path configFilePath;


    @Test
    void backupDirectoryTest() throws IOException, InterruptedException {
        configFilePath = location.resolve("backupDirectory.ini");

        Path backupLocation = location.resolve("backup");
        Path storageLocation = location.resolve("storage");
        backupLocation.toFile().mkdir();
        storageLocation.toFile().mkdir();


        FileUtils.writeStringToFile(configFilePath.toFile(),"backupDirectory = "+ backupLocation.toString(), "UTF-8");

        List<Customer> customers = new ArrayList<>();
        customers.add(CustomerGenerator.generateNewCustomer());

        Configuration configuration = Configuration.LoadIni(configFilePath.toUri().toURL());

        EmbeddedStorageManager storageManager = configuration.setBaseDirectory(storageLocation.toString()).createEmbeddedStorageFoundation().createEmbeddedStorageManager(customers).start();

        Thread.sleep(1000);

        List<File> files = (List<File>) FileUtils.listFiles(backupLocation.toFile(), null, true);

        assertTrue(files.size() > 2, files.toString());

        storageManager.shutdown();
    }
}
```

ends with following error by creating EmbeddedStorageManager:

```
java.lang.RuntimeException: Incompatible parent FileSystem of one.microstream.afs.ADirectory$Default@56637cff:one.microstream.afs.nio.NioFileSystem$Default@2938127d != this (one.microstream.afs.nio.NioFileSystem$Default@127a7272).

	at one.microstream.afs.AFileSystem$Abstract.validateMember(AFileSystem.java:242)
	at one.microstream.storage.types.StorageFileProvider$Builder$Abstract.setDirectory(StorageFileProvider.java:129)
	at one.microstream.storage.types.StorageFileProvider$Builder$Abstract.setDirectory(StorageFileProvider.java:1)
	at one.microstream.storage.types.StorageBackupSetup.New(StorageBackupSetup.java:39)
	at one.microstream.storage.types.Storage.BackupSetup(Storage.java:468)
	at one.microstream.storage.types.Storage.BackupSetup(Storage.java:463)
	at one.microstream.storage.types.Storage.BackupSetup(Storage.java:484)
	at one.microstream.storage.configuration.EmbeddedStorageFoundationCreator$Default.createFoundation(EmbeddedStorageFoundationCreator.java:62)
	at one.microstream.storage.configuration.Configuration.createEmbeddedStorageFoundation(Configuration.java:591)
	at test.microstream.configuration.BackupDirectoryTest.backupDirectoryTest(BackupDirectoryTest.java:42)
```

**Comment by zdenek-jonas** [comment]
ok works
