### ISSUE TITLE
Exception during shutdown

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#148]
HG encountered an exception when calling shutdown:

```
Exception in thread "MicroStream-StorageChannel-0" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disrupting Exceptions:
[user]/logger-storage/channel_0/channel_0_1.dat@2552+329 -> [user]/logger-storage_backup/channel_0/channel_0_1.dat
    at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
    at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:293)
    at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:370)
    at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "main" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disrupting Exceptions:
[user]/logger-storage/channel_0/channel_0_1.dat@2552+329 -> [user]/logger-storage_backup/channel_0/channel_0_1.dat
    at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
    at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:189)
    at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:176)
    at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTaskAndNotifyAll(StorageTaskBroker.java:166)
    at one.microstream.storage.types.StorageTaskBroker$Default.issueChannelShutdown(StorageTaskBroker.java:453)
    at one.microstream.storage.types.StorageSystem$Default.internalShutdown(StorageSystem.java:482)
    at one.microstream.storage.types.StorageSystem$Default.shutdown(StorageSystem.java:568)
    at one.microstream.storage.types.StorageSystemLogging$Default.shutdown(StorageSystemLogging.java:116)
    at one.microstream.storage.types.EmbeddedStorageManager$Default.shutdown(EmbeddedStorageManager.java:347)
    at one.microstream.storage.types.EmbeddedStorageManagerLogging$Default.shutdown(EmbeddedStorageManagerLogging.java:55)
    at one.microstream.storage.logging.MainTestStorageLoggingExperimental.main(MainTestStorageLoggingExperimental.java:56)
```

**Comment by tm-ms** [comment]
What this exception say is:
- EmbeddedStorageManager#shutdown is called.
- This causes a shutdown task to be created and enqueued for being processed
- Before process a task, a check is performed that processing is enabled (i.e. the storage is not shut down)
- While checking, the operation controller finds that there is a a pending problem
- This causes the exception to be thrown.

I noticed that the exception type of the disruption is not assembled.
I improved StorageExceptionDisruptingExceptions#toString to do so, now.
A quick research showed that printed disruption is a backup exception (StorageExceptionBackupCopying).

So there are two questions here:
1.) Why is the backup exception thrown?
2.) Why can the storage still be issued a task when there already was a disrupting exception?

Sadly, I cannot reproduce the exception, so I need the source code that triggered it or a slimmed down version that still reproduces the exception

**Comment by hg-ms** [comment]
```
package one.microstream.storage.logging;

import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import one.microstream.afs.nio.NioFileSystem;
import one.microstream.storage.types.EmbeddedStorage;
import one.microstream.storage.types.EmbeddedStorageFoundation;
import one.microstream.storage.types.EmbeddedStorageFoundationLogging;
import one.microstream.storage.types.EmbeddedStorageManager;
import one.microstream.storage.types.StorageBackupSetup;
import one.microstream.storage.types.StorageConfiguration;
import one.microstream.storage.types.StorageLiveFileProvider;

public class MainTestStorageLoggingExperimental
{
	public static void main(final String[] args)
	{
		
		System.setProperty("flogger.backend_factory", "com.google.common.flogger.backend.log4j2.Log4j2BackendFactory#getInstance");
		//System.setProperty("log4j2.debug", "true");
		
		final NioFileSystem fileSystem = NioFileSystem.New();
				
		final StorageConfiguration configuration = StorageConfiguration.Builder()

			.setStorageFileProvider(StorageLiveFileProvider.New(fileSystem.ensureDirectory(
				Paths.get(System.getProperty("user.home"), "logger-storage"))
				))
			.setBackupSetup(StorageBackupSetup.New(fileSystem.ensureDirectory(
				Paths.get(System.getProperty("user.home"), "logger-storage_backup"))
				))
			
			.createConfiguration();

		final EmbeddedStorageFoundation<?> foundation = EmbeddedStorage.Foundation(configuration);
		
		
		final EmbeddedStorageManager storage = EmbeddedStorageFoundationLogging.New(foundation).start();
		


		final List<Object> list = new ArrayList<>();
		list.add("bla");
		list.add(LocalDateTime.now());
		list.add(new Blub("blub",13));

		storage.setRoot(list);
		storage.storeRoot();
		storage.shutdown();
	}


	static class Blub
	{
		String str;
		int val;

		public Blub(final String str, final int val)
		{
			this.str = str;
			this.val = val;
		}
	}
}
```

**Comment by tm-ms** [comment]
After some searching in the wrong direction and improving the exception message of StorageExceptionDisruptingExceptions in the process, it was actually quite simple in the end:
The backup process validates the written file to ensure that the physical backup file does not have any error. This is mostly a trust building exercise for nervous users, but why not.
This validation uses the StorageFileEntityDataIterator to iterate over the content of the backup file entity by entity.
And in StorageFileEntityDataIterator#fillBuffer, I simply forgot to pass the current file position along.

So when the file has a total length of 10.000 bytes and the current position is at 9.000, the ByteBuffer is set to a limit of 1.000 bytes. But without the current file position, the IO-call tries to fit the whole file in the buffer, which then throws the corresponding exception.

After adding the file position to the read call, the exception no longer occurs in my tests.

**Comment by hg-ms** [comment]
The exception no more occures after the bugfix, issue is resolved
