### ISSUE TITLE
Communication: BasicNonPrimitiveTypesTests failed

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#156]
Project: microstream-test
branch: communication
test path: vmt/communication/src/test/java/one/microstream/communication/BasicNonPrimitiveTypesTests.java

```
one.microstream.com.ComException
	at one.microstream.com.XSockets.acceptSocketChannel(XSockets.java:52)
	at one.microstream.com.ComConnectionListener$Default.listenForConnection(ComConnectionListener.java:52)
	at one.microstream.com.ComConnectionListener$Default.listenForConnection(ComConnectionListener.java:1)
	at one.microstream.com.ComHost$Default.synchAcceptConnection(ComHost.java:169)
	at one.microstream.com.ComHost$Default.acceptConnections(ComHost.java:158)
	at one.microstream.com.ComHost$Default.run(ComHost.java:115)
	at one.microstream.communication.AbstractComTest.lambda$startServer$1(AbstractComTest.java:72)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:254)
	at one.microstream.com.XSockets.acceptSocketChannel(XSockets.java:47)
	... 7 more
```

**Comment by hg-ms** [comment]
This exception is ok as long as it is thrown during the tests shutdown phase. We also changed the tests a litte to catch the exception if it happens during the shutdown.

**Comment by zdenek-jonas** [comment]
Ok.. fixed
