### ISSUE TITLE
Communicaton: BinaryHandlerClassTest failed

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#157]
Project: microstream-test
branch: communication
test path: vmt/communication/src/test/java/one/microstream/communication/BinaryHandlerClassTest.java

```
one.microstream.com.ComException
	at one.microstream.com.XSockets.acceptSocketChannel(XSockets.java:52)
	at one.microstream.com.ComConnectionListener$Default.listenForConnection(ComConnectionListener.java:52)
	at one.microstream.com.ComConnectionListener$Default.listenForConnection(ComConnectionListener.java:1)
	at one.microstream.com.ComHost$Default.synchAcceptConnection(ComHost.java:169)
	at one.microstream.com.ComHost$Default.acceptConnections(ComHost.java:158)
	at one.microstream.com.ComHost$Default.run(ComHost.java:115)
	at one.microstream.communication.AbstractComTest.lambda$startServer$1(AbstractComTest.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:269)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:288)
	at one.microstream.com.XSockets.acceptSocketChannel(XSockets.java:47)
	... 7 more
```

**Comment by hg-ms** [comment]
This exception is ok as long as it is thrown during the tests shutdown phase. We also changed the tests a litte to catch the exception if it happens during the shutdown.

**Comment by zdenek-jonas** [comment]
ok fixed
