### ISSUE TITLE
Communication: one.microstream.meta.NotImplementedYetError for BinaryHandlerPersistenceRootsDefaultTest

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#158]
Trift sporadisch auf.

```
one.microstream.meta.NotImplementedYetError
	at one.microstream.com.ComPersistenceChannel$Abstract.readByObjectIds(ComPersistenceChannel.java:100)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:771)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOnce(BinaryLoader.java:713)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:824)
	at one.microstream.persistence.types.PersistenceManager$Default.get(PersistenceManager.java:379)
	at one.microstream.com.binarydynamic.ComChannelDynamic.receive(ComChannelDynamic.java:74)
	at one.microstream.communication.AbstractComTest.receiveBasicObjectTest(AbstractComTest.java:41)

```

**Comment by hg-ms** [comment]
This one is tricky.
I was not able to reproduce that on my windows machine. 
It is correct that readByObjectIds throws that NotImplementedYetError. It should even not been called, thats the riddle...

**Comment by hg-ms** [comment]
After setting up the microstream dev environment on a linux machine i was able to reproduce the bug.

**Comment by hg-ms** [comment]
fix implemented.

**Comment by zdenek-jonas** [comment]
ok fixed
