### ISSUE TITLE
java.nio.file.Path under Windows and JAVA 11 runtime cannot be saved

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#159]
When i try to save java.nio.file.Path under Windows and JAVA 11 i receive:

For reproduce just try to save class with this path or use Test project
project: Microstream-test
branch: master
test: microstream-test\vmt\intern\src\test\java\test\microstream\handler\BinaryHandlerPath.java

```
one.microstream.persistence.exceptions.PersistenceExceptionTypeNotPersistable: Type not persistable: "class java.lang.ref.WeakReference".

	at one.microstream.persistence.binary.internal.BinaryHandlerUnpersistable.guaranteeSubTypeInstanceViablity(BinaryHandlerUnpersistable.java:78)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.lambda$0(PersistenceTypeHandlerManager.java:247)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.iterateMemberTypes(AbstractBinaryHandlerReflective.java:583)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.recursiveEnsureTypeHandlers(PersistenceTypeHandlerManager.java:240)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandler(PersistenceTypeHandlerManager.java:611)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.internalEnsureTypeHandler(PersistenceTypeHandlerManager.java:588)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:357)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:333)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.registerGuaranteed(BinaryStorer.java:560)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.registerLazyOptional(BinaryStorer.java:575)
	at one.microstream.persistence.types.PersistenceObjectManager$Default.ensureObjectId(PersistenceObjectManager.java:182)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.register(BinaryStorer.java:594)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.apply(BinaryStorer.java:298)
	at one.microstream.persistence.binary.types.BinaryValueFunctions$9.storeValueFromMemory(BinaryValueFunctions.java:147)
	at one.microstream.persistence.binary.types.Binary.storeFixedSize(Binary.java:1205)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.store(AbstractBinaryHandlerReflective.java:497)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.store(AbstractBinaryHandlerReflective.java:1)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.storeItem(BinaryStorer.java:414)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.storeGraph(BinaryStorer.java:403)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.store(BinaryStorer.java:421)
	at one.microstream.persistence.types.PersistenceManager$Default.store(PersistenceManager.java:274)
	at one.microstream.storage.types.StorageConnection.store(StorageConnection.java:308)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.initialize(EmbeddedStorageManager.java:342)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:213)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1)
	at one.microstream.storage.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:624)
	at one.microstream.storage.types.EmbeddedStorage.start(EmbeddedStorage.java:482)
	at test.microstream.handler.AbstractHandlerTest.startStorage(AbstractHandlerTest.java:94)
	at test.microstream.handler.AbstractHandlerTest.saveAndReload(AbstractHandlerTest.java:85)
	at test.microstream.handler.AbstractHandlerTest.saveAndLoadTest(AbstractHandlerTest.java:36)
```

**Comment by hg-ms** [comment]
if running within a java 11 VM (jdk-11.0.3.7-hotspot) the TypeDictionary contains additional entries:

...
```
0000000000001000064 sun.nio.fs.WindowsPath{
	sun.nio.fs.WindowsFileSystem sun.nio.fs.WindowsPath#fs               ,
	sun.nio.fs.WindowsPathType   sun.nio.fs.WindowsPath#type             ,
	java.lang.String             sun.nio.fs.WindowsPath#root             ,
	java.lang.String             sun.nio.fs.WindowsPath#path             ,
	java.lang.ref.WeakReference  sun.nio.fs.WindowsPath#pathForWin32Calls,
	[Ljava.lang.Integer;         sun.nio.fs.WindowsPath#offsets          ,
	int                          sun.nio.fs.WindowsPath#hash             ,
}
0000000000001000065 sun.nio.fs.WindowsFileSystem{
	sun.nio.fs.WindowsFileSystemProvider sun.nio.fs.WindowsFileSystem#provider        ,
	java.lang.String                     sun.nio.fs.WindowsFileSystem#defaultDirectory,
	java.lang.String                     sun.nio.fs.WindowsFileSystem#defaultRoot     ,
}
0000000000001000067 sun.nio.fs.WindowsFileSystemProvider{
	sun.nio.fs.WindowsFileSystem sun.nio.fs.WindowsFileSystemProvider#theFileSystem,
}
0000000000001000070 sun.nio.fs.WindowsPathType{
	enum ABSOLUTE,
	enum UNC,
	enum RELATIVE,
	enum DIRECTORY_RELATIVE,
	enum DRIVE_RELATIVE,
	java.lang.String java.lang.Enum#name   ,
	int              java.lang.Enum#ordinal,
}
0000000000001000071 java.lang.ref.WeakReference{}
```

**Comment by zdenek-jonas** [comment]
OpenJDK 14 also

**Comment by tm-ms** [comment]
Since WindowsPath is just an OS-specific vehicle for the general type Path, it cannot be handled generically itself, but must be handled as the "main" type, "Path". 
I described and explained that in detail in microstream-one/microstream-private#185.

This worked after I implemented it.
If it doesn't work anymore, it should be investigated (debugged) why that is the case.
Normally, all classes implementing Path should be handled by BinaryHandlerPath just as an abstract "Path" entity, not as their actual class. A little debugging should fairly quickly reveal the cause.

Everything else after that is a subsequent error, i.a. WeakReference is intentionally not persistable, but it should not come to analyzing the field typed as a WeakReference in the first place.

**Comment by fh-ms** [comment]
Path type hierarchy:
Java 8: WindowsPath extends AbstractPath which implements Path
Since Java 11: WindowsPath (extends Object) implements Path

The heuristic in PersistenceAbstractTypeHandlerSearcher didn't catch super-interfaces if the concrete type extended java.lang.Object. This is fixed now.

**Comment by zdenek-jonas** [comment]
ok fixed
