### ISSUE TITLE
NPE in StorageLockedFile#Default<init> during import

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#16]
When using StorageConnection#importFiles a NPE is thrown in StorageLockedFile init.

```txt
Exception in thread "main" java.lang.NullPointerException
	at one.microstream.storage.types.StorageLockedFile$Default.<init>(StorageLockedFile.java:131)
	at one.microstream.storage.types.StorageInventoryFile$Default.<init>(StorageInventoryFile.java:55)
	at one.microstream.storage.types.StorageRequestTaskImportData$SourceFileSlice.<init>(StorageRequestTaskImportData.java:460)
	at one.microstream.storage.types.StorageRequestTaskImportData$Default.<init>(StorageRequestTaskImportData.java:70)
	at one.microstream.storage.types.StorageRequestTaskCreator$Default.createImportFromFilesTask(StorageRequestTaskCreator.java:238)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueImportFromFilesTask(StorageTaskBroker.java:309)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.importFiles(StorageRequestAcceptor.java:240)
	at one.microstream.storage.types.StorageConnection$Default.importFiles(StorageConnection.java:424)
```

**Comment by tm-ms** [comment]
The reason for this is that the import task creates a dummy storage file instance with no file lock as the head instance of a queue (constructor call `SourceFileSlice`). But the super class constructor gets the channel from the passed lock.

The import function hasn't been used in ... well, years and obviously some refactoring along the way broke it.

A very quick and easy fix would be to let the channel be null if the lock is null.
But that has to be checked thoroughly with the overall design to prevent unwanted side effects / NPEs at another place.

**Comment by tm-ms** [comment]
Fixed and tested in branch bugfix/Minor_Bugfix_Batch.
