### ISSUE TITLE
Instance != SqlReadableFile Exception when calling ESM.exportChannels w/ sql fs param

### ISSUE THREAD

**Issue by m-stoer** [microstream-one/microstream#160]
Tested on current master (1902595565e4880437fa1f7607baa1929ffdfeb8)

When calling EmbeddedStorageManager.exportChannels() with an SqlFileSystem (MySQL), I get the following exception:
```java
Exception in thread "main" one.microstream.storage.exceptions.StorageException: Problem in channel 0
	at one.microstream.storage.types.StorageChannelTask$Abstract.checkForProblems(StorageChannelTask.java:65)
	at one.microstream.storage.types.StorageChannelTask$Abstract.waitOnCompletion(StorageChannelTask.java:127)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.waitOnTask(StorageRequestAcceptor.java:139)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.exportChannels(StorageRequestAcceptor.java:224)
	at one.microstream.storage.types.StorageConnection$Default.exportChannels(StorageConnection.java:483)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.exportChannels(EmbeddedStorageManager.java:480)
	at one.microstream.storage.types.StorageConnection.exportChannels(StorageConnection.java:237)
	at one.microstream.test.FilesystemCopyIssue.main(FilesystemCopyIssue.java:25)
Caused by: one.microstream.storage.exceptions.StorageException
	at one.microstream.storage.types.StorageFile$Abstract.copyTo(StorageFile.java:277)
	at one.microstream.storage.types.StorageFileManager$Default.lambda$7(StorageFileManager.java:1296)
	at one.microstream.afs.AFS.executeWriting(AFS.java:255)
	at one.microstream.afs.AFS.executeWriting(AFS.java:242)
	at one.microstream.storage.types.StorageFileManager$Default.exportData(StorageFileManager.java:1295)
	at one.microstream.storage.types.StorageChannel$Default.exportData(StorageChannel.java:604)
	at one.microstream.storage.types.StorageRequestTaskExportChannels$Default.internalProcessBy(StorageRequestTaskExportChannels.java:42)
	at one.microstream.storage.types.StorageRequestTaskExportChannels$Default.internalProcessBy(StorageRequestTaskExportChannels.java:1)
	at one.microstream.storage.types.StorageChannelTask$Abstract.processBy(StorageChannelTask.java:201)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:388)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:475)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Instance is not of type "interface one.microstream.afs.sql.SqlReadableFile" and thus cannot be handled: one.microstream.afs.nio.NioWritableFile$Default@631da28f
	at one.microstream.afs.AIoHandler$Abstract.validateHandledReadableFile(AIoHandler.java:451)
	at one.microstream.afs.AIoHandler$Abstract.castReadableFile(AIoHandler.java:467)
	at one.microstream.afs.sql.SqlIoHandler$Default.specificCopyFrom(SqlIoHandler.java:513)
	at one.microstream.afs.sql.SqlIoHandler$Default.specificCopyFrom(SqlIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.copyFrom(AIoHandler.java:918)
	at one.microstream.afs.AWritableFile.copyFrom(AWritableFile.java:55)
	at one.microstream.storage.types.StorageFile$Abstract.copyTo(StorageFile.java:273)
	... 11 more
```

This is the java code:

```java
final MysqlDataSource datasource = new MysqlDataSource();
datasource.setURL("jdbc:mysql://localhost:3306/ms");
datasource.setUser("root");
datasource.setPassword("my-secret-pw");
datasource.setPort(3306);

final SqlFileSystem sqlFs = SqlFileSystem.New(SqlProviderMySql.New(datasource));

final EmbeddedStorageManager storage = EmbeddedStorage.start();
		
storage.exportChannels(StorageLiveFileProvider.New(sqlFs.ensureDirectoryPath("channel-export")));
		
storage.shutdown();
```

Here is how I set up MySQL in an docker environment:
```sh
# Start the MySQL Container
docker run --name ms-servermode-backup-db -e MYSQL_ROOT_PASSWORD=my-secret-pw -dp 3306:3306 mysql

# Start an sh session in the container
docker exec -ti ms-servermode-backup-db sh

# Log into mysql cli
mysql -u root -p

# Create the ms database
CREATE DATABASE ms;
```

**Comment by fh-ms** [comment]
Files from different file systems don't mix. This is a missing feature. If there is a need for this please open a feature request.
