### ISSUE TITLE
AResolving#resolveFilePath resolves file path wrong

### ISSUE THREAD

**Issue by m-stoer** [microstream-one/microstream#161]
On current master (1902595565e4880437fa1f7607baa1929ffdfeb8) the resolveFilePath(final String... pathElements) method in the AResolving interface interprets the path elements wrong and throws an exception.

Code:
```java
final AFileSystem fs = NioFileSystem.New();
final String[] path = new String[] {"MyDir", "MyFile.txt"};
		
final AFile file = fs.ensureFilePath(path);
file.ensureExists();
		
fs.resolveFilePath(path);
```

Exception:
```java
Exception in thread "main" java.lang.RuntimeException: Inconsistent path: identifier of this ("MyDir") does not match the specified identifier "MyFile.txt".
	at one.microstream.afs.ADirectory$Abstract.resolveDirectoryPath(ADirectory.java:506)
	at one.microstream.afs.AFileSystem$Abstract.resolveDirectoryPath(AFileSystem.java:371)
	at one.microstream.afs.AResolving.resolveFilePath(AResolving.java:29)
	at one.microstream.afs.AResolving.resolveFilePath(AResolving.java:11)
	at one.microstream.test.SimpleDemo.main(SimpleDemo.java:69)
```

**Comment by tm-ms** [comment]
After detailed investigation, I found that the logic was pefectly fine, only the validation that throws the exception was misconceived.
And during testing the fix, I found and fixed another bug.
It's happy hour around here: issue one bug to be fixed and get another one fixed for free :-D.

**Comment by tm-ms** [comment]
I also tested this particular code snippet. See class `MainTestAfsEnsurePathPriv412`.
So this issue can be closed right away.
