### ISSUE TITLE
BackupTest failed - one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: 

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#162]
BackupTests in Master failed:

Project: microstream-test
branch: master

Path to test: vmt/intern/src/test/java/test/microstream/configuration/BackupDirectoryTest.java

There are three tests, failed all.
It happens after this commit to master:
https://bitbucket.org/microstreamone/microstream/commits/320eb4da25af55aa0f7abff94fa2b4a6369cc1d1

callstack:
```
Exception in thread "MicroStream-StorageBackupHandler" one.microstream.storage.exceptions.StorageExceptionBackupCopying: /tmp/junit4785676440238506316/storage/channel_0/transactions_0.sft@0+26 -> /tmp/junit4785676440238506316/backup/channel_0/transactions_0.sft
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:471)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:485)
	at one.microstream.storage.types.StorageBackupItemQueue$Default$Item.processBy(StorageBackupItemQueue.java:178)
	at one.microstream.storage.types.StorageBackupItemQueue$Default.processNextItem(StorageBackupItemQueue.java:109)
	at one.microstream.storage.types.StorageBackupHandler$Default.run(StorageBackupHandler.java:212)
	at java.lang.Thread.run(Thread.java:748)
Caused by: one.microstream.exceptions.IORuntimeException: java.nio.file.NoSuchFileException: /tmp/junit4785676440238506316/backup/channel_0/transactions_0.sft
	at one.microstream.io.XIO$unchecked.size(XIO.java:1444)
	at one.microstream.afs.nio.NioIoHandler$Default.subjectFileSize(NioIoHandler.java:115)
	at one.microstream.afs.nio.NioIoHandler$Default.subjectFileSize(NioIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.size(AIoHandler.java:499)
	at one.microstream.afs.AFile.size(AFile.java:67)
	at one.microstream.storage.types.StorageFile$Abstract.size(StorageFile.java:117)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:448)
	... 5 more
Caused by: java.nio.file.NoSuchFileException: /tmp/junit4785676440238506316/backup/channel_0/transactions_0.sft
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at one.microstream.io.XIO.size(XIO.java:410)
	at one.microstream.io.XIO$unchecked.size(XIO.java:1440)
	... 11 more


one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:/tmp/junit4785676440238506316/storage/channel_0/transactions_0.sft@0+26 -> /tmp/junit4785676440238506316/backup/channel_0/transactions_0.sft,}

	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:189)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:176)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTaskAndNotifyAll(StorageTaskBroker.java:166)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueRootsLoadTask(StorageTaskBroker.java:399)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.recallRoots(StorageRequestAcceptor.java:181)
	at one.microstream.storage.types.EmbeddedStorageBinarySource$Default.read(EmbeddedStorageBinarySource.java:53)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOnce(BinaryLoader.java:707)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:824)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.loadRoots(BinaryLoader.java:869)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.loadExistingRoots(EmbeddedStorageManager.java:305)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.initialize(EmbeddedStorageManager.java:325)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:213)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1)
	at test.microstream.configuration.BackupDirectoryTest.backupDirectoryTest(BackupDirectoryTest.java:83)
```

**Comment by zdenek-jonas** [comment]
I can simulate this problem with following code (without configuration library)

```
package test.microstream;

import one.microstream.afs.ADirectory;
import one.microstream.afs.AFileSystem;
import one.microstream.afs.nio.NioFileSystem;
import one.microstream.storage.types.*;

import java.io.File;
import java.nio.file.Path;

public class Backup {

    public static void main(String[] args) throws InterruptedException {
        File file = new File("/tmp/aaa");
        file.mkdir();
        Path location = file.toPath();


        Path backupPath = location.resolve("backup");

        AFileSystem aFileSystem = NioFileSystem.New();
        ADirectory backupDir = aFileSystem.ensureDirectoryPath(backupPath.toFile().getAbsolutePath());
        ADirectory dataDir = aFileSystem.ensureDirectoryPath(location.toFile().getAbsolutePath());

        StorageBackupSetup backupSetup = StorageBackupSetup.New(
                StorageBackupFileProvider.New(backupDir)
        );

        StorageLiveFileProvider provider = StorageLiveFileProvider.New(dataDir);

        EmbeddedStorageFoundation foundation = EmbeddedStorage.Foundation(
                Storage.ConfigurationBuilder()
                        .setBackupSetup(backupSetup)
                        .setStorageFileProvider(provider)
        );

        Basic basic = new Basic();

        EmbeddedStorageManager storageManager = foundation.createEmbeddedStorageManager();

        storageManager.start();
        storageManager.setRoot(basic);
        storageManager.storeRoot();
        storageManager.shutdown();

    }

    static class Basic {
        String value = "ahoj";
    }
}

```

and the Exception stack is:
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -javaagent:/snap/intellij-idea-community/252/lib/idea_rt.jar=41823:/snap/intellij-idea-community/252/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/home/jonas/devel/microstream-test/vmt/intern/target/classes:/home/jonas/.m2/repository/one/microstream/storage.embedded/03.02.00-MS-GA-SNAPSHOT/storage.embedded-03.02.00-MS-GA-20200921.020533-23.jar:/home/jonas/.m2/repository/one/microstream/storage/03.02.00-MS-GA-SNAPSHOT/storage-03.02.00-MS-GA-20200921.020533-23.jar:/home/jonas/.m2/repository/one/microstream/persistence.binary/03.02.00-MS-GA-SNAPSHOT/persistence.binary-03.02.00-MS-GA-20200921.020531-23.jar:/home/jonas/.m2/repository/one/microstream/persistence/03.02.00-MS-GA-SNAPSHOT/persistence-03.02.00-MS-GA-20200921.020529-23.jar:/home/jonas/.m2/repository/one/microstream/base/03.02.00-MS-GA-SNAPSHOT/base-03.02.00-MS-GA-20200921.020527-23.jar:/home/jonas/.m2/repository/one/microstream/storage.embedded.configuration/03.02.00-MS-GA-SNAPSHOT/storage.embedded.configuration-03.02.00-MS-GA-20200921.020534-23.jar:/home/jonas/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/home/jonas/.m2/repository/org/javassist/javassist/3.26.0-GA/javassist-3.26.0-GA.jar:/home/jonas/.m2/repository/com/github/javafaker/javafaker/0.18/javafaker-0.18.jar:/home/jonas/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/jonas/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/jonas/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/jonas/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar test.microstream.Backup
Exception in thread "MicroStream-StorageBackupHandler" one.microstream.storage.exceptions.StorageExceptionBackupCopying: /tmp/aaa/channel_0/transactions_0.sft@0+26 -> /tmp/aaa/backup/channel_0/transactions_0.sft
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:471)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:485)
	at one.microstream.storage.types.StorageBackupItemQueue$Default$Item.processBy(StorageBackupItemQueue.java:178)
	at one.microstream.storage.types.StorageBackupItemQueue$Default.processNextItem(StorageBackupItemQueue.java:109)
	at one.microstream.storage.types.StorageBackupHandler$Default.run(StorageBackupHandler.java:212)
	at java.lang.Thread.run(Thread.java:748)
Caused by: one.microstream.exceptions.IORuntimeException: java.nio.file.NoSuchFileException: /tmp/aaa/backup/channel_0/transactions_0.sft
	at one.microstream.io.XIO$unchecked.size(XIO.java:1444)
	at one.microstream.afs.nio.NioIoHandler$Default.subjectFileSize(NioIoHandler.java:115)
	at one.microstream.afs.nio.NioIoHandler$Default.subjectFileSize(NioIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.size(AIoHandler.java:499)
	at one.microstream.afs.AFile.size(AFile.java:67)
	at one.microstream.storage.types.StorageFile$Abstract.size(StorageFile.java:117)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:448)
	... 5 more
Caused by: java.nio.file.NoSuchFileException: /tmp/aaa/backup/channel_0/transactions_0.sft
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at one.microstream.io.XIO.size(XIO.java:410)
	at one.microstream.io.XIO$unchecked.size(XIO.java:1440)
	... 11 more
Exception in thread "main" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:/tmp/aaa/channel_0/transactions_0.sft@0+26 -> /tmp/aaa/backup/channel_0/transactions_0.sft,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:189)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:176)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTaskAndNotifyAll(StorageTaskBroker.java:166)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueRootsLoadTask(StorageTaskBroker.java:399)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.recallRoots(StorageRequestAcceptor.java:181)
	at one.microstream.storage.types.EmbeddedStorageBinarySource$Default.read(EmbeddedStorageBinarySource.java:53)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOnce(BinaryLoader.java:707)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:824)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.loadRoots(BinaryLoader.java:869)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.loadExistingRoots(EmbeddedStorageManager.java:305)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.initialize(EmbeddedStorageManager.java:325)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:213)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1)
	at test.microstream.Backup.main(Backup.java:41)
Exception in thread "MicroStream-StorageChannel-0" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:/tmp/aaa/channel_0/transactions_0.sft@0+26 -> /tmp/aaa/backup/channel_0/transactions_0.sft,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:398)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:475)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1

```

**Comment by fh-ms** [comment]
Regression introduced with microstream-one/microstream-public#155, backup files' creation must be ensured.
Probably a job of the `StorageBackupHandler` ?

**Comment by tm-ms** [comment]
I added a fix based on the suggestion of FH.

**Comment by zdenek-jonas** [comment]
Ok fixed
