### ISSUE TITLE
AFS - File is not created (Import from CSV does not work)

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#169]
I have a little bit crazy test, to test a csv export and import:
Source code is at the end of this issue text.

the line:
`reimportConverter.convertCsv(storageFile);`

produce error:
```
one.microstream.exceptions.IORuntimeException: java.nio.file.NoSuchFileException: /var/folders/nn/sgrnwx896wj8mttc8pcxjxb00000gn/T/junit6996968433872397429/reimport/java.math.BigInteger_37.dat
	at one.microstream.io.XIO$unchecked.size(XIO.java:1463)
	at one.microstream.afs.nio.NioIoHandler$Default.subjectFileSize(NioIoHandler.java:148)
	at one.microstream.afs.nio.NioIoHandler$Default.specificSize(NioIoHandler.java:166)
	at one.microstream.afs.nio.NioIoHandler$Default.specificSize(NioIoHandler.java:1)
	at one.microstream.afs.AIoHandler$Abstract.size(AIoHandler.java:502)
	at one.microstream.afs.AReadableFile.size(AReadableFile.java:51)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.setTargetFile(StorageDataConverterTypeCsvToBinary.java:1056)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.beginTable(StorageDataConverterTypeCsvToBinary.java:1719)
	at one.microstream.chars.XCsvParserCharArray.parseSegment(XCsvParserCharArray.java:837)
	at one.microstream.chars.XCsvParserCharArray.parseSingletonSegment(XCsvParserCharArray.java:712)
	at one.microstream.chars.XCsvParserCharArray.parseSegments(XCsvParserCharArray.java:644)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.parseSegments(StorageDataConverterTypeCsvToBinary.java:1753)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.parseSegments(StorageDataConverterTypeCsvToBinary.java:1)
	at one.microstream.chars.XCsvParserCharArray.parseCsvData(XCsvParserCharArray.java:973)
	at one.microstream.chars.XCsvParserCharArray.parseCsvData(XCsvParserCharArray.java:1)
	at one.microstream.util.xcsv.XCsvParser.parseCsvData(XCsvParser.java:21)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.parseCurrentFile(StorageDataConverterTypeCsvToBinary.java:1076)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.convertCsv(StorageDataConverterTypeCsvToBinary.java:1672)
	at one.microstream.storage.types.StorageDataConverterTypeCsvToBinary$Default.convertCsv(StorageDataConverterTypeCsvToBinary.java:1)
	at test.microstream.export.ExportTest.exportToCSVTest(ExportTest.java:96)

Caused by: java.nio.file.NoSuchFileException: /var/folders/nn/sgrnwx896wj8mttc8pcxjxb00000gn/T/junit6996968433872397429/reimport/java.math.BigInteger_37.dat
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at one.microstream.io.XIO.size(XIO.java:421)
	at one.microstream.io.XIO$unchecked.size(XIO.java:1459)
```

a little bit debugging:
In ADirectory.java is method:
`	@Override
		public final AFile ensureFile(final String identifier, final String name, final String type)
`
This should create file, but this file is not created at all.

Test ca be found in project: microstream-test
Branch: master
Path: vmt/intern/src/test/java/test/microstream/export/ExportTest.java

Just uncomment annotation @Test
To build this project and download actual dependency use command: `mvn clean install -DskipTests -U`

```
package test.microstream.export;

import one.microstream.afs.ADirectory;
import one.microstream.afs.AFile;
import one.microstream.afs.AReadableFile;
import one.microstream.afs.nio.NioFileSystem;
import one.microstream.storage.types.*;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

class ExportTest {

    @TempDir
    Path location;

    @Test
    void exportToCSVTest() {
        List<Customer> customers = new ArrayList<>();
        customers.add(CustomerGenerator.generateNewCustomer());
        customers.add(CustomerGenerator.generateNewCustomer());
        customers.add(CustomerGenerator.generateNewCustomer());
        customers.add(CustomerGenerator.generateNewCustomer());
        customers.add(CustomerGenerator.generateNewCustomer());


        Path exportPathBin = location.resolve("export");

        EmbeddedStorageManager storage = EmbeddedStorage.start(customers, location);

        final NioFileSystem fs = NioFileSystem.New();

        final ADirectory exportPathDir = fs.ensureDirectoryPath(exportPathBin.toFile().getAbsolutePath());

        StorageEntityTypeExportStatistics exportResult = storage.exportTypes(
                new StorageEntityTypeExportFileProvider.Default(exportPathDir, "bin"));

        //get all exported binary files
        List<String> binaryFiles = new ArrayList<>();
        exportResult.typeStatistics().values().forEach(v -> binaryFiles.add(v.file().identifier()));

        Path csvPath = location.resolve("csv");

        final ADirectory aCsvDir = fs.ensureDirectoryPath(csvPath.toFile().getAbsolutePath());

        //create the CSV converter
        StorageDataConverterTypeBinaryToCsv converter =
                new StorageDataConverterTypeBinaryToCsv.UTF8(
                        StorageDataConverterCsvConfiguration.defaultConfiguration(),
                        new StorageEntityTypeConversionFileProvider.Default(aCsvDir, "csv"),
                        storage.typeDictionary(),
                        null, // no type name mapping
                        4096, // read buffer size
                        4096  // write buffer size
                );

        //convert all binary files to CSV files

        for (String file : binaryFiles) {
            AReadableFile dataFile = exportPathDir.ensureFile(file).useReading();
            converter.convertDataFile(dataFile);
        }

        List<File> files = (List<File>) FileUtils.listFiles(csvPath.toFile(), null, true);
        assertTrue(files.size() > 10);

//        //reimport

        Path reimportStoragePath = location.resolve("reimport");
        reimportStoragePath.toFile().mkdir();
        ADirectory reimportStorage = fs.ensureDirectoryPath(reimportStoragePath.toFile().getAbsolutePath());

        StorageDataConverterTypeCsvToBinary<AFile> reimportConverter =
                StorageDataConverterTypeCsvToBinary.New(
                        StorageDataConverterCsvConfiguration.defaultConfiguration(),
                        storage.typeDictionary(),
                        new StorageEntityTypeConversionFileProvider.Default(reimportStorage, "dat")
                );

        for (File file : files) {
            AReadableFile storageFile = aCsvDir.ensureFile(file.getName()).useReading();
            try {
                reimportConverter.convertCsv(storageFile);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                storageFile.close();
            }
        }
        List<File> datFiles = (List<File>) FileUtils.listFiles(reimportStoragePath.toFile(), null, true);
        assertTrue(datFiles.size() > 10, files.toString());

    }

}

```
```
package test.microstream.export;

import com.github.javafaker.Faker;

public class CustomerGenerator {

    private static Faker faker = new Faker();

    private CustomerGenerator() {
        // prevent instantiate
    }

    public static Customer generateNewCustomer() {
        return new Customer(faker.name().firstName(), faker.name().lastName(), faker.address().streetName(), faker.address().streetAddressNumber());
    }
}

```

**Comment by fh-ms** [comment]
Added missing AFile#ensureExists in StorageEntityTypeConversionFileProvider.

**Comment by zdenek-jonas** [comment]
OK
