### ISSUE TITLE
AFS REDIS after save first couple of elements crash: Physical length 110 of current head file 2 is not equal its expected length of 131

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#170]
Just start this program:
[microstream-test.tar.gz](https://github.com/microstream-one/microstream-private/files/5678929/microstream-test.tar.gz)

It happens with more channels:

Start configuration:
```
         AFileSystem aFileSystem = BlobStoreFileSystem.New(
                RedisConnector.Caching("redis://localhost:6379/0")
        );

        ADirectory aDirectory = aFileSystem.ensureDirectoryPath("microstream");

        StorageConfiguration configuration = StorageConfiguration.Builder()
                .setStorageFileProvider(Storage.FileProvider(aDirectory))
                .setChannelCountProvider(StorageChannelCountProvider.New(16))
                .createConfiguration();

        EmbeddedStorageManager storageManager = EmbeddedStorage.start(root, configuration);

```

run docker image:

`docker run -p 6379:6379 redis:6.0.9-alpine`

```
Exception in thread "main" one.microstream.persistence.exceptions.PersistenceExceptionTransfer
	at one.microstream.storage.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:68)
	at one.microstream.storage.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:1)
	at one.microstream.persistence.binary.types.BinaryStorer$Default.commit(BinaryStorer.java:481)
	at one.microstream.persistence.types.PersistenceManager$Default.store(PersistenceManager.java:278)
	at one.microstream.storage.types.StorageConnection.store(StorageConnection.java:308)
	at StartUbuntu.main(StartUbuntu.java:83)
Caused by: one.microstream.storage.exceptions.StorageException: Problem in channel 3
	at one.microstream.storage.types.StorageChannelTask$Abstract.checkForProblems(StorageChannelTask.java:65)
	at one.microstream.storage.types.StorageChannelTask$Abstract.waitOnCompletion(StorageChannelTask.java:124)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.waitOnTask(StorageRequestAcceptor.java:139)
	at one.microstream.storage.types.StorageRequestAcceptor$Default.storeData(StorageRequestAcceptor.java:157)
	at one.microstream.storage.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:64)
	... 5 more
Caused by: one.microstream.storage.exceptions.StorageException: Physical length 110 of current head file 2 is not equal its expected length of 131
	at one.microstream.storage.types.StorageFileManager$Default.ensureHeadFileTotalLength(StorageFileManager.java:563)
	at one.microstream.storage.types.StorageFileManager$Default.storeChunks(StorageFileManager.java:583)
	at one.microstream.storage.types.StorageChannel$Default.storeEntities(StorageChannel.java:531)
	at one.microstream.storage.types.StorageRequestTaskStoreEntities$Default.internalProcessBy(StorageRequestTaskStoreEntities.java:59)
	at one.microstream.storage.types.StorageRequestTaskStoreEntities$Default.internalProcessBy(StorageRequestTaskStoreEntities.java:1)
	at one.microstream.storage.types.StorageChannelTask$Abstract.processBy(StorageChannelTask.java:201)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:388)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:475)
	at java.base/java.lang.Thread.run(Thread.java:834)

Process finished with exit code 1



```

**Comment by zdenek-jonas** [comment]
fixed
