### ISSUE TITLE
ZoneID is not compatible between MS version 3 and actual release. 

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#175]
When the type `java.time.ZoneId` is saved in MS version 3, it cannot be loaded with actual MS snapshot version:

This problem has been probably created with fix of issue: https://github.com/microstream-one/microstream-private/issues/502

```
13:30:40  one.microstream.persistence.exceptions.PersistenceExceptionTypeConsistency: TypeId inconsistency for java.time.ZoneId: typeDictionary type definition typeId = 1000075, validated type handler typeId = 69
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.validateTypeHandler(PersistenceTypeHandlerManager.java:290)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandler(PersistenceTypeHandlerManager.java:603)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.internalEnsureTypeHandler(PersistenceTypeHandlerManager.java:588)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:357)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.lambda$0(PersistenceTypeHandlerManager.java:244)
13:30:40  	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerReflective.iterateMemberTypes(AbstractBinaryHandlerReflective.java:583)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.recursiveEnsureTypeHandlers(PersistenceTypeHandlerManager.java:240)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.initialRegisterTypeHandlers(PersistenceTypeHandlerManager.java:686)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.synchInternalInitialize(PersistenceTypeHandlerManager.java:957)
13:30:40  	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.initialize(PersistenceTypeHandlerManager.java:930)
13:30:40  	at one.microstream.storage.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:754)
13:30:40  	at one.microstream.storage.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:624)
13:30:40  	at one.microstream.storage.types.EmbeddedStorage.start(EmbeddedStorage.java:484)

```

**Comment by zdenek-jonas** [comment]
For retest: Just remove code in compatibility/consumer/src/test/java/one/microstream/ReadTypeTest.java:27

**Comment by fh-ms** [comment]
Actually a type handler for ZoneOffset was sufficient. ZoneRegion was working well. And we are able to keep the binary format, so the compatibility issue resolves itself.

**Comment by zdenek-jonas** [comment]
ok, works
