### ISSUE TITLE
Changing enum content: Storage startup fails with "PersistenceException: Unknown TypeId"

### ISSUE THREAD

**Issue by JMMSW** [microstream-one/microstream#209]
Starting a storage fails with error "PersistenceException: Unknown TypeId" when there is a enum that was changed in a certain way:

- first needs to be a change in the enum entry order
- second, a new enum entry has to be added.

A example project was added:
See "org.example.msenumtest.ms.EnumExampleA"
[ExampleProject.zip](https://github.com/microstream-one/microstream-private/files/6075904/ExampleProject.zip)

The Error:
[Error.txt](https://github.com/microstream-one/microstream-private/files/6075903/Error.txt)
`
Exception in thread "main" one.microstream.persistence.exceptions.PersistenceException: Unknown TypeId: 1000069
	at one.microstream.persistence.types.PersistenceRootResolver$Default.resolveRootEnumConstants(PersistenceRootResolver.java:293)
	at one.microstream.persistence.types.PersistenceRootResolver$Default.resolveRootInstance(PersistenceRootResolver.java:273)
	at one.microstream.persistence.types.PersistenceRootResolver$MappingWrapper.resolveRootInstance(PersistenceRootResolver.java:388)
	at one.microstream.persistence.types.PersistenceRootResolver.resolveRootEntries(PersistenceRootResolver.java:47)
	at one.microstream.persistence.types.BinaryHandlerPersistenceRootsDefault.updateState(BinaryHandlerPersistenceRootsDefault.java:140)
	at one.microstream.persistence.types.BinaryHandlerPersistenceRootsDefault.updateState(BinaryHandlerPersistenceRootsDefault.java:1)
	at one.microstream.persistence.types.PersistenceTypeHandler.initializeState(PersistenceTypeHandler.java:70)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.buildInstances(BinaryLoader.java:443)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.build(BinaryLoader.java:382)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:825)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.loadRoots(BinaryLoader.java:869)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.loadExistingRoots(EmbeddedStorageManager.java:306)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.initialize(EmbeddedStorageManager.java:326)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:214)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1)
	at one.microstream.storage.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:626)
	at one.microstream.storage.types.EmbeddedStorage.start(EmbeddedStorage.java:443)
	at org.example.msenumtest.App.main(App.java:18)
`

**Comment by hg-ms** [comment]
A short analysis:

Step 1:
Stores the enum and register it as root with id 100 and root-entry "enum 100"

Step 2:
Creates a legacy typehandler mapping from id 100 to id 102.
Tthe root constants will be changed to "enum 102".
The stored enum instance won't be updated!

Step 3:
Creates a legacy typehandler mapping from id 100 to id 103, but not for type 102 to 103 as the instance stored in step still has id 100 because it was not updated (stored again).
legacy type handlers are only created for typeIDs that are found in the storage during initialization (see StorageIdAnalysis). Id 102 will not be found.
During root initialization the PersistenceRootResolver tries to resolve "enum 100" and will fail with the "Unknown TypeId: 100" exception because there no (legacy) type-handler has been created.

Possible solutions:

- Create type handlers for all types in the type-dictionary at startup.
(one.microstream.storage.embedded.types.EmbeddedStorageManager.Default.ensureRequiredTypeHandlers())

- Try to create required handlers during root initializations if necessary.
(one.microstream.persistence.types.PersistenceRootResolver.Default.resolveRootEnumConstants(String)

Workaround:
add a legacy type mapping from the missing type to an existing e.g.:
```
final EmbeddedStorageManager storage = EmbeddedStorage.Foundation()
    .setRefactoringMappingProvider(
        PersistenceRefactoringMappingProvider.New(
            EqHashTable.New(X.KeyValue("enum 1000069", "enum 1000068"))))
    .start();

```

**Comment by hg-ms** [comment]
PR #373 tries to create the missing legacy-type handler automatically.
