### ISSUE TITLE
StorageViewer Error if connecting to a Storage without persisted "root"

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#210]
If connecting to a new storage that has no previously peristed root, the Viewer shows internal errors instead of a empty "Root":
```
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:942)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:739)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:623)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:621)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)
	at one.microstream.storage.restclient.jersey.types.StorageRestClientJersey$Default.requestObject(StorageRestClientJersey.java:146)
	at one.microstream.storage.restclient.types.StorageView$Default.root(StorageView.java:57)
	at one.microstream.storage.restclient.app.ui.StorageViewDataProvider.lambda$0(StorageViewDataProvider.java:25)
	at one.microstream.storage.restclient.app.ui.StorageViewDataProvider$Default.fetchChildrenFromBackEnd(StorageViewDataProvider.java:94)
```
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$getJsonItems$3(DataCommunicator.java:620)
```

**Comment by hg-ms** [comment]
fix in branch: bug/StorageViewerEmptyRoot_210
also update dependencies

**Comment by zdenek-jonas** [comment]
Maybe, I am doing something wrong, but is still see the same problem:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/17253582/167823247-5cc9f089-41ac-439a-8a83-86520856047a.png">

**Comment by zdenek-jonas** [comment]
Ok, works
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/17253582/167833846-cb8809a6-78c0-4445-a332-40522e2bb280.png">
