### ISSUE TITLE
Problem when running with Configuration.Default() .setBaseDirectoryInUserHome("data-dir").setBackupDirectory("backup-dir")

### ISSUE THREAD

**Issue by notsharable** [microstream-one/microstream#222]
Hi,

with this config
final EmbeddedStorageManager storageManager = Configuration.Default()
			    .setBaseDirectoryInUserHome("data-dir")
			    .setBackupDirectory("backup-dir")
			    .setChannelCount(2)
			    .createEmbeddedStorageFoundation()
				.createEmbeddedStorageManager();

If I keep .setChannelCount(2), everything works fine the first time I run  the code (with no pre-existing data directories)
But I get the following exception message when I run the second time (without deleting the pre-existing data directories).
Exception in thread "MicroStream-StorageChannel-1" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:C:/Users/DND/data-dir/channel_1/channel_1_1.dat@2262+0 -> backup-dir/channel_1/channel_1_1.dat,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:398)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:475)
	at java.base/java.lang.Thread.run(Thread.java:834)
Root after storing root = Root: Hello World @!Wed Apr 21 19:15:12 CEST 2021
Exception in thread "main" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:C:/Users/DND/data-dir/channel_1/channel_1_1.dat@2262+0 -> backup-dir/channel_1/channel_1_1.dat,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:189)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:176)
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTaskAndNotifyAll(StorageTaskBroker.java:166)
	at one.microstream.storage.types.StorageTaskBroker$Default.issueChannelShutdown(StorageTaskBroker.java:453)
	at one.microstream.storage.types.StorageSystem$Default.internalShutdown(StorageSystem.java:499)
	at one.microstream.storage.types.StorageSystem$Default.shutdown(StorageSystem.java:585)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.shutdown(EmbeddedStorageManager.java:349)
	at org.dnd.datastore.ConfigTypesExperimentApp.withCodeConfig(ConfigTypesExperimentApp.java:79)
	at org.dnd.datastore.ConfigTypesExperimentApp.main(ConfigTypesExperimentApp.java:16)
Exception in thread "MicroStream-StorageChannel-0" one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageExceptionBackupCopying:C:/Users/DND/data-dir/channel_1/channel_1_1.dat@2262+0 -> backup-dir/channel_1/channel_1_1.dat,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:119)
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:398)
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:475)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "MicroStream-StorageBackupHandler" one.microstream.storage.exceptions.StorageExceptionBackupCopying: C:/Users/DND/data-dir/channel_1/channel_1_1.dat@2262+0 -> backup-dir/channel_1/channel_1_1.dat
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:470)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:484)
	at one.microstream.storage.types.StorageBackupItemQueue$Default$Item.processBy(StorageBackupItemQueue.java:178)
	at one.microstream.storage.types.StorageBackupItemQueue$Default.processNextItem(StorageBackupItemQueue.java:109)
	at one.microstream.storage.types.StorageBackupHandler$Default.run(StorageBackupHandler.java:212)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: one.microstream.storage.exceptions.StorageExceptionBackupCopying: C:/Users/DND/data-dir/channel_1/channel_1_1.dat@2262+0 -> backup-dir/channel_1/channel_1_1.dat
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:461)
	... 5 more
Caused by: one.microstream.storage.exceptions.StorageException
	at one.microstream.storage.types.StorageFile$Abstract.copyFrom(StorageFile.java:359)
	at one.microstream.storage.types.StorageFile$Abstract.copyTo(StorageFile.java:263)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:451)
	... 5 more
Caused by: one.microstream.exceptions.IndexBoundsException: Index out of bounds: 2262 not in [0;2262[ (StartIndex >= bound)
	at one.microstream.afs.AIoHandler$Abstract.copyGeneric(AIoHandler.java:354)
	at one.microstream.afs.AIoHandler$Abstract.copyTo(AIoHandler.java:898)
	at one.microstream.afs.AWritableFile.copyTo(AWritableFile.java:50)
	at one.microstream.storage.types.StorageFile$Abstract.copyFrom(StorageFile.java:355)
	... 7 more

With .setChannelCount(**4**), the problem occurs at the first run (with no pre-existing data directories).

Any idea why?
Thnaks and kind regards

**Comment by hg-ms** [comment]
The class one.microstream.storage.configuration.Configuration has been marked deprecated already in version 07.00.00-MS-GA . The replacement is one.microstream.storage.embedded.configuration.types.EmbeddedStorageConfigurationBuilder.
Therefore we won’t fix that bug.
