### ISSUE TITLE
StorageConnection.getObject(final long objectId) hang at 0fbeda31 Revision

### ISSUE THREAD

**Issue by 54446776** [microstream-one/microstream#308]
## Environment Details
* MicroStream Version: 07.00.00-MS-GA-SNAPSHOT
* JDK version: 17.0.1
* OS: macOS Monterey
* Used frameworks: none

## Describe the bug
pull 0fbeda31 and compile, unit test hang.
program working fine with Revision e131a08c.

unit test start log:
15:35:51.575 INFO  one.microstream.util.logging.Logging - MicroStream Version 07.00.00-MS-GA-SNAPSHOT
15:35:51.582 INFO  o.m.c.t.ConfigurationLoader$FileLoader - Loading configuration: /xxxxxx.yaml (UTF-8)
15:35:51.711 INFO  o.m.s.e.t.EmbeddedStorageFoundation$Default - Creating embedded storage manager
15:35:57.180 INFO  o.m.p.t.PersistenceTypeHandlerManager$Default - Initializing type handler manager
15:36:33.112 INFO  o.m.s.e.t.EmbeddedStorageManager$Default - Starting embedded storage manager
15:36:33.113 INFO  o.m.s.types.StorageSystem$Default - Starting storage system
15:37:00.656 INFO  o.m.p.t.PersistenceTypeHandlerManager$Default - Initializing type handler manager
15:37:38.875 INFO  o.m.s.e.t.EmbeddedStorageManager$Default - Embedded storage manager initialized
15:38:58.309 INFO  o.m.p.t.PersistenceTypeHandlerManager$Default - Initializing type handler manager
program hang...

debug steps stop at  StorageConnection.getObject method (line 435), it's hang. StorageConnection.getObject method is called from my first time to fetch object from graph db.
	
	public default Object getObject(final long objectId)
	{
		return this.persistenceManager().getObject(objectId);
	}

open database --> ok
get root --> ok
get object from root --> hang

My code work well with revision before e131a08c(include e131a08c). 
But start with revision 0fbeda31 (include ed93cf70) , unit test is hang (DB is made with same revision code).

DB Configuration is simple, just one line customization:
foundation.onConnectionFoundation(BinaryHandlersJDK8::registerJDK8TypeHandlers);
YAML config:
channel-count: 1
housekeeping-interval: 60000
data-file-maximum-size: 2097152000

## To Reproduce
Step by step instructions to reproduce the problem.

**Comment by hg-ms** [comment]
Hello,
As our tests don’t show any problems regrading the latest commits and I was not able to reproduce that behavior in a simple scenario I assume that there is a jet not known condition that causes the stall.

May I ask you to provide a thread dump of the hanging unit test if possible?

**Comment by 54446776** [comment]
2022-02-09 19:59:47
Full thread dump Java HotSpot(TM) 64-Bit Server VM (17.0.1+12-LTS-39 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x0000600030edff40, length=20, elements={
0x000000015380d200, 0x0000000153863600, 0x0000000154a08800, 0x0000000153863c00,
0x0000000153864200, 0x0000000153864800, 0x0000000153864e00, 0x0000000143042e00,
0x0000000153023000, 0x0000000143043400, 0x0000000134072200, 0x0000000134074a00,
0x0000000133a66800, 0x0000000154b57e00, 0x0000000154fea800, 0x000000012b08f000,
0x000000013434e200, 0x0000000133cda400, 0x00000001534b7400, 0x0000000133387400
}

"main" #1 prio=5 os_prio=31 cpu=704.23ms elapsed=19.05s tid=0x000000015380d200 nid=0x2803 waiting for monitor entry  [0x000000016b6d2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at one.microstream.reference.LazyReferenceManager$Default.register(LazyReferenceManager.java:453)
        - waiting to lock <0x000000070a758cc8> (a one.microstream.reference.LazyReferenceManager$Default)
        at one.microstream.reference.Lazy.register(Lazy.java:166)
        at one.microstream.persistence.binary.one.microstream.reference.BinaryHandlerLazyDefault.create(BinaryHandlerLazyDefault.java:132)
        at one.microstream.persistence.binary.one.microstream.reference.BinaryHandlerLazyDefault.create(BinaryHandlerLazyDefault.java:1)
        at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustom.create(AbstractBinaryHandlerCustom.java:1)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:232)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:185)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:173)
        at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:286)
        at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:295)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:833)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:803)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:871)
        - locked <0x000000070c72b7e0> (a one.microstream.persistence.internal.DefaultObjectRegistry)
        at one.microstream.persistence.types.PersistenceManager$Default.getObject(PersistenceManager.java:406)
        at one.microstream.storage.types.StorageConnection.getObject(StorageConnection.java:435)
        at one.microstream.storage.types.Database$Default.getObject(Database.java:165)
        at one.microstream.reference.Lazy$Default.load(Lazy.java:424)
        - locked <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at one.microstream.reference.Lazy$Default.get(Lazy.java:405)
        - locked <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at xxx

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.47ms elapsed=19.06s tid=0x0000000153863600 nid=0x4403 waiting on condition  [0x000000016c526000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.1/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@17.0.1/Reference.java:253)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.1/Reference.java:215)

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.06ms elapsed=19.06s tid=0x0000000154a08800 nid=0x4303 in Object.wait()  [0x000000016c732000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.1/Native Method)
        - waiting on <0x0000000700000af8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:155)
        - locked <0x0000000700000af8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.1/Finalizer.java:172)

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.25ms elapsed=19.06s tid=0x0000000153863c00 nid=0xa503 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.29ms elapsed=19.06s tid=0x0000000153864200 nid=0x5903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=31 cpu=0.30ms elapsed=19.06s tid=0x0000000153864800 nid=0xa203 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=31 cpu=854.97ms elapsed=19.06s tid=0x0000000153864e00 nid=0x5a03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"C1 CompilerThread0" #10 daemon prio=9 os_prio=31 cpu=313.32ms elapsed=19.06s tid=0x0000000143042e00 nid=0x9f03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
        - None

"Sweeper thread" #11 daemon prio=9 os_prio=31 cpu=0.01ms elapsed=19.06s tid=0x0000000153023000 nid=0x9e03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Common-Cleaner" #12 daemon prio=8 os_prio=31 cpu=0.48ms elapsed=19.05s tid=0x0000000143043400 nid=0x5d03 in Object.wait()  [0x000000016d69e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.1/Native Method)
        - waiting on <0x0000000700001c90> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:155)
        - locked <0x0000000700001c90> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@17.0.1/CleanerImpl.java:140)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)
        at jdk.internal.misc.InnocuousThread.run(java.base@17.0.1/InnocuousThread.java:162)

   Locked ownable synchronizers:
        - None

"Monitor Ctrl-Break" #13 daemon prio=5 os_prio=31 cpu=7.31ms elapsed=18.96s tid=0x0000000134072200 nid=0x5e03 runnable  [0x000000016d8aa000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.SocketDispatcher.read0(java.base@17.0.1/Native Method)
        at sun.nio.ch.SocketDispatcher.read(java.base@17.0.1/SocketDispatcher.java:47)
        at sun.nio.ch.NioSocketImpl.tryRead(java.base@17.0.1/NioSocketImpl.java:261)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.1/NioSocketImpl.java:312)
        at sun.nio.ch.NioSocketImpl.read(java.base@17.0.1/NioSocketImpl.java:350)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.1/NioSocketImpl.java:803)
        at java.net.Socket$SocketInputStream.read(java.base@17.0.1/Socket.java:966)
        at sun.nio.cs.StreamDecoder.readBytes(java.base@17.0.1/StreamDecoder.java:270)
        at sun.nio.cs.StreamDecoder.implRead(java.base@17.0.1/StreamDecoder.java:313)
        at sun.nio.cs.StreamDecoder.read(java.base@17.0.1/StreamDecoder.java:188)
        - locked <0x00000007000018b8> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(java.base@17.0.1/InputStreamReader.java:177)
        at java.io.BufferedReader.fill(java.base@17.0.1/BufferedReader.java:162)
        at java.io.BufferedReader.readLine(java.base@17.0.1/BufferedReader.java:329)
        - locked <0x00000007000018b8> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(java.base@17.0.1/BufferedReader.java:396)
        at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:49)

   Locked ownable synchronizers:
        - <0x0000000700038d58> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"Notification Thread" #14 daemon prio=9 os_prio=31 cpu=0.03ms elapsed=18.96s tid=0x0000000134074a00 nid=0x9b03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"MicroStream-StorageChannel-0" #16 prio=5 os_prio=31 cpu=2713.06ms elapsed=18.31s tid=0x0000000133a66800 nid=0x6503 in Object.wait()  [0x000000016ef2e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.1/Native Method)
        - waiting on <0x0000000796a992f8> (a one.microstream.storage.types.StorageRequestTaskLoadByOids$Default)
        at one.microstream.storage.types.StorageTask$Abstract.awaitNext(StorageTask.java:90)
        - locked <0x0000000796a992f8> (a one.microstream.storage.types.StorageRequestTaskLoadByOids$Default)
        at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:470)
        at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:519)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - None

"Attach Listener" #17 daemon prio=9 os_prio=31 cpu=82.47ms elapsed=17.99s tid=0x0000000154b57e00 nid=0x8c03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-0" #18 daemon prio=9 os_prio=31 cpu=2.10ms elapsed=14.51s tid=0x0000000154fea800 nid=0x7303 runnable  [0x00000002c3ea2000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.accept(java.base@17.0.1/Native Method)
        at sun.nio.ch.NioSocketImpl.accept(java.base@17.0.1/NioSocketImpl.java:755)
        at java.net.ServerSocket.implAccept(java.base@17.0.1/ServerSocket.java:675)
        at java.net.ServerSocket.platformImplAccept(java.base@17.0.1/ServerSocket.java:641)
        at java.net.ServerSocket.implAccept(java.base@17.0.1/ServerSocket.java:617)
        at java.net.ServerSocket.implAccept(java.base@17.0.1/ServerSocket.java:574)
        at java.net.ServerSocket.accept(java.base@17.0.1/ServerSocket.java:532)
        at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(jdk.management.agent@17.0.1/LocalRMIServerSocketFactory.java:52)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(java.rmi@17.0.1/TCPTransport.java:413)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(java.rmi@17.0.1/TCPTransport.java:377)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - <0x000000073e351c78> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"RMI TCP Connection(1)-127.0.0.1" #19 daemon prio=9 os_prio=31 cpu=75.14ms elapsed=14.48s tid=0x000000012b08f000 nid=0x7403 runnable  [0x00000002c40ad000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.poll(java.base@17.0.1/Native Method)
        at sun.nio.ch.NioSocketImpl.park(java.base@17.0.1/NioSocketImpl.java:181)
        at sun.nio.ch.NioSocketImpl.timedRead(java.base@17.0.1/NioSocketImpl.java:285)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.1/NioSocketImpl.java:309)
        at sun.nio.ch.NioSocketImpl.read(java.base@17.0.1/NioSocketImpl.java:350)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.1/NioSocketImpl.java:803)
        at java.net.Socket$SocketInputStream.read(java.base@17.0.1/Socket.java:966)
        at java.io.BufferedInputStream.fill(java.base@17.0.1/BufferedInputStream.java:244)
        at java.io.BufferedInputStream.read(java.base@17.0.1/BufferedInputStream.java:263)
        - locked <0x000000073e902220> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@17.0.1/FilterInputStream.java:82)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(java.rmi@17.0.1/TCPTransport.java:569)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(java.rmi@17.0.1/TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(java.rmi@17.0.1/TCPTransport.java:705)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$250/0x0000000800edf6b8.run(java.rmi@17.0.1/Unknown Source)
        at java.security.AccessController.executePrivileged(java.base@17.0.1/AccessController.java:776)
        at java.security.AccessController.doPrivileged(java.base@17.0.1/AccessController.java:399)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(java.rmi@17.0.1/TCPTransport.java:704)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.1/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.1/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - <0x000000073e9025a8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
        - <0x000000074520a8b0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"RMI Scheduler(0)" #20 daemon prio=9 os_prio=31 cpu=0.24ms elapsed=14.47s tid=0x000000013434e200 nid=0x7603 waiting on condition  [0x00000002c42ba000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.1/Native Method)
        - parking to wait for  <0x000000073ea00170> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.1/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@17.0.1/AbstractQueuedSynchronizer.java:1672)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.1/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.1/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.1/ThreadPoolExecutor.java:1062)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.1/ThreadPoolExecutor.java:1122)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.1/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - None

"JMX server connection timeout 21" #21 daemon prio=9 os_prio=31 cpu=3.24ms elapsed=14.46s tid=0x0000000133cda400 nid=0x7703 in Object.wait()  [0x00000002c44c6000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.1/Native Method)
        - waiting on <0x000000073ec00170> (a [I)
        at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(java.management@17.0.1/ServerCommunicatorAdmin.java:171)
        - locked <0x000000073ec00170> (a [I)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - None

"RMI TCP Connection(2)-127.0.0.1" #22 daemon prio=9 os_prio=31 cpu=34.26ms elapsed=13.21s tid=0x00000001534b7400 nid=0xa80f runnable  [0x00000002c48dd000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.poll(java.base@17.0.1/Native Method)
        at sun.nio.ch.NioSocketImpl.park(java.base@17.0.1/NioSocketImpl.java:181)
        at sun.nio.ch.NioSocketImpl.timedRead(java.base@17.0.1/NioSocketImpl.java:285)
        at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.1/NioSocketImpl.java:309)
        at sun.nio.ch.NioSocketImpl.read(java.base@17.0.1/NioSocketImpl.java:350)
        at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.1/NioSocketImpl.java:803)
        at java.net.Socket$SocketInputStream.read(java.base@17.0.1/Socket.java:966)
        at java.io.BufferedInputStream.fill(java.base@17.0.1/BufferedInputStream.java:244)
        at java.io.BufferedInputStream.read(java.base@17.0.1/BufferedInputStream.java:263)
        - locked <0x00000007999dac40> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@17.0.1/FilterInputStream.java:82)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(java.rmi@17.0.1/TCPTransport.java:569)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(java.rmi@17.0.1/TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(java.rmi@17.0.1/TCPTransport.java:705)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$250/0x0000000800edf6b8.run(java.rmi@17.0.1/Unknown Source)
        at java.security.AccessController.executePrivileged(java.base@17.0.1/AccessController.java:776)
        at java.security.AccessController.doPrivileged(java.base@17.0.1/AccessController.java:399)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(java.rmi@17.0.1/TCPTransport.java:704)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.1/ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.1/ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)

   Locked ownable synchronizers:
        - <0x000000073e351af0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        - <0x0000000799958620> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"LazyReferenceManager@1565713391" #23 prio=5 os_prio=31 cpu=0.83ms elapsed=12.62s tid=0x0000000133387400 nid=0x7c03 waiting for monitor entry  [0x00000002c4aea000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at one.microstream.reference.Lazy$Default.peek(Lazy.java:295)
        - waiting to lock <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at one.microstream.reference.LazyReferenceManager$Default$1.accept(LazyReferenceManager.java:330)
        at one.microstream.reference.LazyReferenceManager$Default$1.accept(LazyReferenceManager.java:1)
        at one.microstream.reference.LazyReferenceManager$Default.iterate(LazyReferenceManager.java:621)
        - locked <0x000000070a758cc8> (a one.microstream.reference.LazyReferenceManager$Default)
        at one.microstream.reference.LazyReferenceManager$Default.countReferences(LazyReferenceManager.java:323)
        at one.microstream.reference.LazyReferenceManager$Default.internalCleanUp(LazyReferenceManager.java:388)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUp(LazyReferenceManager.java:487)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUpBudgeted(LazyReferenceManager.java:439)
        at one.microstream.reference.LazyReferenceManager$Default$LazyReferenceCleanupThread.run(LazyReferenceManager.java:663)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=31 cpu=438.83ms elapsed=19.07s tid=0x0000000152f0b510 nid=0x3d03 runnable  

"GC Thread#0" os_prio=31 cpu=330.91ms elapsed=19.07s tid=0x0000000152f07380 nid=0x3203 runnable  

"GC Thread#1" os_prio=31 cpu=315.76ms elapsed=18.73s tid=0x0000000132f1e0c0 nid=0x9a03 runnable  

"GC Thread#2" os_prio=31 cpu=303.63ms elapsed=18.73s tid=0x000000015400cf90 nid=0x6203 runnable  

"GC Thread#3" os_prio=31 cpu=335.37ms elapsed=18.73s tid=0x0000000152e0d0f0 nid=0x9703 runnable  

"GC Thread#4" os_prio=31 cpu=333.69ms elapsed=18.73s tid=0x000000015400d530 nid=0x9503 runnable  

"GC Thread#5" os_prio=31 cpu=309.25ms elapsed=18.73s tid=0x0000000142e0edd0 nid=0x9403 runnable  

"GC Thread#6" os_prio=31 cpu=311.88ms elapsed=18.73s tid=0x0000000132f1e540 nid=0x9203 runnable  

"GC Thread#7" os_prio=31 cpu=303.70ms elapsed=18.73s tid=0x0000000152e0da30 nid=0x9003 runnable  

"GC Thread#8" os_prio=31 cpu=311.39ms elapsed=18.73s tid=0x000000015400dda0 nid=0x6403 runnable  

"G1 Main Marker" os_prio=31 cpu=0.45ms elapsed=19.07s tid=0x0000000142e04400 nid=0x4f03 runnable  

"G1 Conc#0" os_prio=31 cpu=473.00ms elapsed=19.07s tid=0x0000000142e04c80 nid=0x3403 runnable  

"G1 Conc#1" os_prio=31 cpu=485.61ms elapsed=14.35s tid=0x0000000142fa7690 nid=0x7903 runnable  

"G1 Refine#0" os_prio=31 cpu=133.61ms elapsed=19.07s tid=0x0000000154004370 nid=0x4b03 runnable  

"G1 Refine#1" os_prio=31 cpu=62.96ms elapsed=17.72s tid=0x0000000154019690 nid=0x6703 runnable  

"G1 Refine#2" os_prio=31 cpu=62.14ms elapsed=17.72s tid=0x0000000152e1a900 nid=0x8903 runnable  

"G1 Refine#3" os_prio=31 cpu=54.09ms elapsed=17.72s tid=0x0000000132f23b20 nid=0x6903 runnable  

"G1 Refine#4" os_prio=31 cpu=52.66ms elapsed=17.72s tid=0x00000001058095c0 nid=0x6b03 runnable  

"G1 Refine#5" os_prio=31 cpu=47.61ms elapsed=17.72s tid=0x0000000142f13530 nid=0x6d03 runnable  

"G1 Refine#6" os_prio=31 cpu=53.86ms elapsed=17.72s tid=0x00000001058099e0 nid=0x8203 runnable  

"G1 Refine#7" os_prio=31 cpu=40.58ms elapsed=17.72s tid=0x0000000105a041c0 nid=0x8103 runnable  

"G1 Refine#8" os_prio=31 cpu=36.09ms elapsed=17.72s tid=0x00000001059041c0 nid=0x8003 runnable  

"G1 Service" os_prio=31 cpu=1.46ms elapsed=19.07s tid=0x0000000152f07800 nid=0x4a03 runnable  

"VM Periodic Task Thread" os_prio=31 cpu=6.71ms elapsed=18.97s tid=0x0000000132f1b0e0 nid=0x6003 waiting on condition  

JNI global refs: 24, weak refs: 0


Found one Java-level deadlock:
=============================
"main":
  waiting to lock monitor 0x000060000321b190 (object 0x000000070a758cc8, a one.microstream.reference.LazyReferenceManager$Default),
  which is held by "LazyReferenceManager@1565713391"

"LazyReferenceManager@1565713391":
  waiting to lock monitor 0x000060000322c820 (object 0x00000007983d7ea8, a one.microstream.reference.Lazy$Default),
  which is held by "main"

Java stack information for the threads listed above:
===================================================
"main":
        at one.microstream.reference.LazyReferenceManager$Default.register(LazyReferenceManager.java:453)
        - waiting to lock <0x000000070a758cc8> (a one.microstream.reference.LazyReferenceManager$Default)
        at one.microstream.reference.Lazy.register(Lazy.java:166)
        at one.microstream.persistence.binary.one.microstream.reference.BinaryHandlerLazyDefault.create(BinaryHandlerLazyDefault.java:132)
        at one.microstream.persistence.binary.one.microstream.reference.BinaryHandlerLazyDefault.create(BinaryHandlerLazyDefault.java:1)
        at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustom.create(AbstractBinaryHandlerCustom.java:1)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:232)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:185)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:173)
        at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:286)
        at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:295)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:833)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:803)
        at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:871)
        - locked <0x000000070c72b7e0> (a one.microstream.persistence.internal.DefaultObjectRegistry)
        at one.microstream.persistence.types.PersistenceManager$Default.getObject(PersistenceManager.java:406)
        at one.microstream.storage.types.StorageConnection.getObject(StorageConnection.java:435)
        at one.microstream.storage.types.Database$Default.getObject(Database.java:165)
        at one.microstream.reference.Lazy$Default.load(Lazy.java:424)
        - locked <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at one.microstream.reference.Lazy$Default.get(Lazy.java:405)
        - locked <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at xxx
"LazyReferenceManager@1565713391":
        at one.microstream.reference.Lazy$Default.peek(Lazy.java:295)
        - waiting to lock <0x00000007983d7ea8> (a one.microstream.reference.Lazy$Default)
        at one.microstream.reference.LazyReferenceManager$Default$1.accept(LazyReferenceManager.java:330)
        at one.microstream.reference.LazyReferenceManager$Default$1.accept(LazyReferenceManager.java:1)
        at one.microstream.reference.LazyReferenceManager$Default.iterate(LazyReferenceManager.java:621)
        - locked <0x000000070a758cc8> (a one.microstream.reference.LazyReferenceManager$Default)
        at one.microstream.reference.LazyReferenceManager$Default.countReferences(LazyReferenceManager.java:323)
        at one.microstream.reference.LazyReferenceManager$Default.internalCleanUp(LazyReferenceManager.java:388)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUp(LazyReferenceManager.java:487)
        at one.microstream.reference.LazyReferenceManager$Default.cleanUpBudgeted(LazyReferenceManager.java:439)
        at one.microstream.reference.LazyReferenceManager$Default$LazyReferenceCleanupThread.run(LazyReferenceManager.java:663)

Found 1 deadlock.

**Comment by hg-ms** [comment]
Many thanks for the tread dump. It is quite informative. Seems that there is a concurrency problem with Lazy-References and the lazy reference manager.

**Comment by hg-ms** [comment]
The cause of the deadlock is related to PR #306.
In the LazyReferenceManager the private method “countReferences” is used to create some logging output. This method can cause a deadlock if Lazy-References are loaded at the same time.

A fix that replaces the dangerous logging is available here:
https://github.com/microstream-one/microstream/tree/deadlockInLazyReferenceManager_fix_308

@fh-ms: please have a lock at it if the logging is adequate.

**Comment by 54446776** [comment]
bug fixed. thx for the quick response.
