### ISSUE TITLE
Backup thread ignores storage shutdown

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#4]
When the storage is explicitely shutdown, an existing backup thread will just continue to work through its item queue. However, as a shutdown closes the StorageFiles' FileChannels, it will encounter a a corresponding exception. Not always (race condition), but fairly easily reproducible.

Of course, the backup thread (more precisely: the StorageBackupHandler implementation) has to consider a shutdown of the parent storage.
This will be a bit tricky: even checking for the shutdown state(s) might still end up in the same exception since there would still be a race condition. Probably the proper way of checking would be:
- Check if a source file is closed on every backup action.
- If so, check if the parent storage is shut down.
- If yes, just terminate. Otherwise, throw an exception.

That some enqueued backup items won't be a problem since the backup content is synchronized with the actual storage content during initialization and any missing backups are then performed.
It might only be relevant as a shutdown option: stop all activities but wait with the actual shutdown until the backup item queue is empty. But this cannot be the default/mandatory behavior since waiting for those backups might take considerable time that might not be worth it.
Or if the requirements become stricter in terms that without an exception, the backup has to be guaranteed to the last byte, then it might become mandatory.

As always, the best strategy is to allow both and make it configurable. The only question then will be which behavior to be set as the default, but that is technically trivial.

**Comment by zdenek-jonas** [comment]
[INFO] Running demo.samples.BackupDBTest
Exception in thread "StorageBackupHandler" one.microstream.storage.exceptions.StorageExceptionBackupCopying: /tmp/BackupStorageApp_work/channel_0/transactions_0.sft@2032+18 -> /tmp/BackupStorageApp_bkup/channel_0/transactions_0.sft
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:468)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:482)
	at one.microstream.storage.types.StorageBackupItemQueue$Default$Item.processBy(StorageBackupItemQueue.java:170)
	at one.microstream.storage.types.StorageBackupItemQueue$Default.processNextItem(StorageBackupItemQueue.java:104)
	at one.microstream.storage.types.StorageBackupHandler$Default.run(StorageBackupHandler.java:186)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: one.microstream.storage.exceptions.StorageExceptionBackupCopying: /tmp/BackupStorageApp_work/channel_0/transactions_0.sft@2032+18 -> /tmp/BackupStorageApp_bkup/channel_0/transactions_0.sft
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:459)
	... 5 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:152)
	at java.base/sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:660)
	at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:442)
	... 5 more
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.992 s <<< FAILURE! - in demo.samples.BackupDBTest
[ERROR] backupDBTest  Time elapsed: 5.984 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1100> but was: <1099>
	at demo.samples.BackupDBTest.backupDBTest(BackupDBTest.java:108)

[INFO] Running demo.samples.UpdateDBTest

**Comment by tm-ms** [comment]
The pasted stack trace only occured on AdoptOpenJDK and Oracle JDK 14 early access.
(Which is kind of strange...)

**Comment by zdenek-jonas** [comment]
Not only, after several hours of testing this bug happens also on others JDKs.

**Comment by tm-ms** [comment]
Implementing microstream-one/microstream-private#183 implicitely covered this issue as well:
When the storage is deactivated, all threads (including the backup thread) must properly terminate and cleanup their held resources (e.g. close opened files).

**Comment by tm-ms** [comment]
The backup thread now properly heeds the storage shutdown.
However, there is still a problem regarding microstream-one/microstream-private#183, but by design:
Even when the storage is shut down, the backup thread processes all of its enqueued items. Otherwise, the backup would be incomplete. In turn, this means that the backup threads keeps storage files opened a little longer that what the storage manager reports as being shutdown.
So there is still a little more work to be done regarding the management of "actually" being shutdown (or more precisely: being completely inactive after being shutdown), but this is of no concern for this issue, here.
As far as this issue is concerned, the backup thread heeding the storage shutdown, everything is done.
Hence issue is closed. For more information on the described problem, see microstream-one/microstream-private#183.
