### ISSUE TITLE
Corrupted database with MariaDB while stress testing

### ISSUE THREAD

**Issue by hypnoze** [microstream-one/microstream#453]
## Environment Details
* MicroStream Version: 07.01.00-MS-GA
* JDK version: 17.0.2
* OS: Windows 11 22H2
* Used frameworks: SpringBoot, MariaDB

## Describe the bug
I was doing some stress tests with JMeter for GET and POST, when I stumbled on a pretty nasty behavior.
When too many store occurs simultaneously, the database get corrupted, and there is no way to fix it, other than deleting it. 

I was using a complex structure for my first tries, so I tried with simpler dataRoot to see if the bug still applied, and it does.
I also tried to upgrade my MariaDB to see if it solved the problem, but it doesn't (I'm now on 10.9.3-MariaDB)

Below is the error I get when it crashes doing the stress test :

```
one.microstream.storage.exceptions.StorageExceptionDisruptingExceptions: Disruptions: {one.microstream.storage.exceptions.StorageException:null,}
	at one.microstream.storage.types.StorageOperationController$Default.checkProcessingEnabled(StorageOperationController.java:139) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:211) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTask(StorageTaskBroker.java:198) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueTaskAndNotifyAll(StorageTaskBroker.java:188) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageTaskBroker$Default.enqueueStoreTask(StorageTaskBroker.java:400) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageRequestAcceptor$Default.storeData(StorageRequestAcceptor.java:177) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:86) ~[microstream-storage-embedded-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageBinaryTarget$Default.write(EmbeddedStorageBinaryTarget.java:1) ~[microstream-storage-embedded-07.01.00-MS-GA.jar:na]
	at one.microstream.persistence.binary.types.BinaryStorer$Default.commit(BinaryStorer.java:531) ~[microstream-persistence-binary-07.01.00-MS-GA.jar:na]
	at one.microstream.persistence.types.PersistenceManager$Default.store(PersistenceManager.java:305) ~[microstream-persistence-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageConnection.store(StorageConnection.java:381) ~[microstream-storage-07.01.00-MS-GA.jar:na]
```

And this is the error I get when I restart
```
Caused by: one.microstream.storage.exceptions.StorageException: Problem in channel #1
	at one.microstream.storage.types.StorageChannelTask$Abstract.checkForProblems(StorageChannelTask.java:114) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelTask$Abstract.waitOnCompletion(StorageChannelTask.java:173) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageSystem$Default.startThreads(StorageSystem.java:336) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageSystem$Default.internalStartUp(StorageSystem.java:518) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageSystem$Default.start(StorageSystem.java:603) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageSystem$Default.start(StorageSystem.java:1) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:246) ~[microstream-storage-embedded-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1) ~[microstream-storage-embedded-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.embedded.types.EmbeddedStorageFoundation.start(EmbeddedStorageFoundation.java:246) ~[microstream-storage-embedded-07.01.00-MS-GA.jar:na]
	at fr.axopen.Recrutement.config.DatabaseConfig.storageManager(DatabaseConfig.java:57) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.4.jar:5.3.4]
	... 35 common frames omitted
Caused by: one.microstream.storage.exceptions.StorageExceptionIoWriting: null
	at one.microstream.storage.types.StorageFileWriter.truncateFile(StorageFileWriter.java:176) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFileWriter.truncate(StorageFileWriter.java:151) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFileManager$Default.handleLastFile(StorageFileManager.java:1335) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFileManager$Default.initializeForExistingFiles(StorageFileManager.java:1027) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFileManager$Default.initializeStorage(StorageFileManager.java:909) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannel$Default.initializeStorage(StorageChannel.java:768) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelTaskInitialize$Default.succeed(StorageChannelTaskInitialize.java:204) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelTaskInitialize$Default.succeed(StorageChannelTaskInitialize.java:1) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelSynchronizingTask$AbstractCompletingTask.synchronizedComplete(StorageChannelSynchronizingTask.java:84) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelSynchronizingTask$AbstractCompletingTask.complete(StorageChannelSynchronizingTask.java:132) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannelTask$Abstract.processBy(StorageChannelTask.java:268) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannel$Default.work(StorageChannel.java:428) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageChannel$Default.run(StorageChannel.java:520) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: one.microstream.storage.exceptions.StorageExceptionConsistency: Reopened file has inconsistent size: Expected size 816644 != actual size 816676.
	at one.microstream.storage.types.StorageLiveDataFile$Default.internalOpenWriting(StorageLiveDataFile.java:286) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFile$Abstract.ensureWritable(StorageFile.java:409) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFile$Abstract.truncate(StorageFile.java:385) ~[microstream-storage-07.01.00-MS-GA.jar:na]
	at one.microstream.storage.types.StorageFileWriter.truncateFile(StorageFileWriter.java:172) ~[microstream-storage-07.01.00-MS-GA.jar:na]
```

I've tried using Postgresql to see if it's only on MariaDB, and it seems to be, Postgresql works fine.

## To Reproduce
I have a simple app

DataRoot.java 
```java
public class DataRoot {
    public List<Long> ids = new ArrayList<>();
}
```
DatabaseConfig.java
```java
@Component
public class DatabaseConfig {

    @Value("${microstream.store.location}")
    private String table;
    @Value("${spring.datasource.url}")
    private String url;
    @Value("${spring.datasource.username}")
    private String username;
    @Value("${spring.datasource.password}")
    private String password;

    @Bean(name = "storageManager")
    private EmbeddedStorageManager storageManager() throws SQLException {
        MariaDbDataSource dataSource = new MariaDbDataSource();
        dataSource.setUrl(this.url);
        dataSource.setUser(this.username);
        dataSource.setPassword(this.password);
        ADirectory fileSystem = SqlFileSystem.New(
                SqlConnector.Caching(
                        SqlProviderMariaDb.New(dataSource)
                )
        ).ensureDirectoryPath(table);
        return EmbeddedStorageFoundation.New()
                .setConfiguration(
                        StorageConfiguration.Builder()
                                .setStorageFileProvider(Storage.FileProvider(fileSystem))
                                .setChannelCountProvider(StorageChannelCountProvider.New(4))
                                .createConfiguration()
                )
                .onConnectionFoundation(cf -> {
                    cf.setClassLoaderProvider(ClassLoaderProvider.New(Thread.currentThread().getContextClassLoader()));
                })
                .setDataBaseName("microstream2")
                .start(new DataRoot());
    }
}
```
RepositoryMS.java
```java
@Component
public class RepositoryMSImpl implements RepositoryMS<Long> {

    private final EmbeddedStorageManager storage;

    public RepositoryMSImpl(@Qualifier("storageManager") EmbeddedStorageManager storageManager) {
        super();
        this.storage = storageManager;
    }

    @Override
    public void add(final Long id) {
        XThreads.executeSynchronized(() -> {
            DataRoot root = getRoot();
            root.ids.add(id);
            storage.store(root.ids);
        });
    }

    private DataRoot getRoot() {
        return (DataRoot) this.storage.root();
    }
}
```
Controller.java
```java
@RestController
@RequestMapping("/api/chantier")
public class ChantierController {

    private final RepositoryMSImpl repositoryMS;

    public ChantierController(RepositoryMSImpl repositoryMS) {
        this.repositoryMS = repositoryMS;
    }

    @PutMapping("")
    public ResponseEntity addRandom() {
        this.repositoryMS.add(getRandomLong(0, 10000000));
        return ResponseEntity.ok().build();
    }

    private Long getRandomLong(int min, int max) {
        Random rand = new Random();
        return (long) (rand.nextInt(max - min) + min);
    }
}
```

I also used a simple JMeter script which spam hundreds of concurrents requests to the API, until it crashes

## Screenshots
Here is also a screenshot of the database metrics during the test, including the crash.
![image](https://user-images.githubusercontent.com/33163419/193054866-2ae5d9ba-2745-4a4a-a449-d4746de417ca.png)

Maybe something's wrong in my configuration, but this bug seems pretty huge, considering it could corrupt production database.  

I have also tried restarting the database service or my computer, but once the database is corrupted I have found no other solution than deleting it.

**Comment by hg-ms** [comment]
Many thanks for the detailed error report.
I was able to reproduce that problem if using MariaDB as storage target.
The problem does not occur if the channel count is reduced to one.
The problem does not occur if the local nio file system is used as storage target.

As a workaround I’d suggest reducing the channel count to one or using a Nio-FS as storage target.

**Comment by hypnoze** [comment]
Thank you for your quick answer !

I tried with 1 channel, and I have the same behaviour 
![image](https://user-images.githubusercontent.com/33163419/193525689-06d1ff85-249d-4f04-a46e-3457dc5fb285.png)

I guess working with any other DB could be a workaround (althought I only tried PSQL), I just wanted to warn you about MariaDB.
