### ISSUE TITLE
CDI integration not working with Quarkus

### ISSUE THREAD

**Issue by jelemux** [microstream-one/microstream#454]
## Is your feature request related to a problem? Please describe.
The CDI integration does not work with Quarkus, because Quarkus' CDI implementation intentionally will not support Synthetic Beans. For that reason an `UnsatisfiedResolutionException` is thrown for `StorageExtension`.

## Describe the solution you'd like
Quarkus provides an alternative way to register extensions: https://quarkus.io/guides/writing-extensions#synthetic_beans
It would be nice if there was such an extension to replace the missing functionality.

## Describe alternatives you've considered
I've considered writing it myself, but I quickly was overwhelmed by the complexity of this task.

## Additional context
```
2022-10-08 02:11:57,721 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type one.microstream.integrations.cdi.types.extension.StorageExtension and qualifiers [@Default]
	- java member: one.microstream.integrations.cdi.types.config.StorageManagerProducer#storageExtension
	- declared on CLASS bean [types=[one.microstream.integrations.cdi.types.config.StorageManagerProducer, java.lang.Object], qualifiers=[@Default, @Any], target=one.microstream.integrations.cdi.types.config.StorageManagerProducer]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1214)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:284)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:140)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:517)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by rdebusscher** [comment]
Hi,

Quarkus integration will be provided through this Quarkus extension https://github.com/microstream-one/microstream/pull/422

regards
Rudy
