### ISSUE TITLE
Spring integration not working

### ISSUE THREAD

**Issue by whisper-bye** [microstream-one/microstream#455]
## Environment Details
* MicroStream Version: 07.01.00-MS-GA
* JDK version: 17.0.4
* OS: macOS
* Used frameworks: e.g. MicroFramework X, Spring, ... Spring

## Describe the bug

Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'root' is expected to be of type 'com.example.demo.repository.Root' but was actually of type 'com.example.demo.repository.Root'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1401) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.23.jar:5.3.23]
	... 24 common frames omitted

State if the problem is easily reproducible or happens intermittently.

easily reproducible

Include stack traces or command outputs

## To Reproduce
Step by step instructions to reproduce the problem.

## Additional context

[demo.zip](https://github.com/microstream-one/microstream/files/9738569/demo.zip)

**Comment by zdenek-jonas** [comment]
I just check your code. You have disabled 'use-current-thread-class-loader'. Please set it true, and then it should works. 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/17253582/194902724-3e8ba921-686c-47ce-ba5c-9ed60dc304d8.png">
