### ISSUE TITLE
when export the microstream data ,  type Definition mismatch: 43:java.util.ArrayList

### ISSUE THREAD

**Issue by yqbjtu** [microstream-one/microstream#575]
## Environment Details
* microstream 8.0
* jdk: 17
* OS: mac
* no framework

## Describe the bug
I have microsteam storage, which is upgraded from microstream 7.0 to 8.0.  During the upgrading, I store the object to microstream 8.0 LazyArrayList from the old storage

the project use microstream 7.0, then I upgrade my dependency to microstream 8.0

when I use the export function, the following error shows:
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" one.microstream.persistence.exceptions.PersistenceException: Type Definition mismatch: 43:java.util.ArrayList
	at one.microstream.persistence.types.PersistenceTypeDictionaryManager.validateTypeDefinition(PersistenceTypeDictionaryManager.java:58)
	at one.microstream.persistence.types.PersistenceTypeDictionaryManager$Abstract.validateTypeDefinitions(PersistenceTypeDictionaryManager.java:188)
	at one.microstream.persistence.types.PersistenceTypeDictionaryManager$Abstract.registerRuntimeTypeDefinitions(PersistenceTypeDictionaryManager.java:162)
	at one.microstream.persistence.types.PersistenceTypeDictionaryManager$Exporting.registerRuntimeTypeDefinitions(PersistenceTypeDictionaryManager.java:320)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.synchUnvalidatedRegisterTypeHandlers(PersistenceTypeHandlerManager.java:676)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandlers(PersistenceTypeHandlerManager.java:658)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.initialRegisterTypeHandlers(PersistenceTypeHandlerManager.java:701)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.synchInternalInitialize(PersistenceTypeHandlerManager.java:984)
	at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.initialize(PersistenceTypeHandlerManager.java:957)
	at one.microstream.storage.embedded.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:803)
	at one.microstream.storage.embedded.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:613)
	at one.microstream.storage.embedded.types.EmbeddedStorage.start(EmbeddedStorage.java:501)
	at one.microstream.storage.embedded.types.EmbeddedStorage.start(EmbeddedStorage.java:348)
	at com.yq.demo.cell.microstream.enumdemo.ExportData.main(ExportData.java:29)

## To Reproduce
use the following code to export the data from microstream 

## Expected behavior
the csv data is exported
```public class ExportData {

    private final static String DATA_DIR = "/metalist/meta";

    public static void main(final String[] args)
    {
        NioFileSystem fileSystem = NioFileSystem.New();

        EmbeddedStorageManager storage    = EmbeddedStorage.start(
                fileSystem.ensureDirectoryPath(DATA_DIR)
        );

        StorageConnection                 connection   = storage.createConnection();
        StorageEntityTypeExportStatistics exportResult = connection.exportTypes(
                fileSystem.ensureDirectoryPath("export-dir")
        );

        StorageDataConverterTypeBinaryToCsv converter = StorageDataConverterTypeBinaryToCsv.New(
                fileSystem.ensureDirectoryPath("csv-dir"),
                storage.typeDictionary()
        );
        converter.convertDataFiles(exportResult.files());

        log.info("done");
    }

}

```

**Comment by hg-ms** [comment]
The exception is thrown at the storage startup, thus not related to the export. The cause of that problem seems to be related to the change from ArrayList to LazyArrayList you mentioned.
How exactly did you do that conversion?

The exception itself is thrown because the type definition of java.util.ArrayList, that has been loaded from the type dictionary, does not match to the actual class. Why that definition does not match is hard to say. Normally definitions for standard java classes don’t change. You may have a look at the PersistenceTypeDictionary.ptd file, the definition for java.util.ArrayList should be
```
0000000000000000043 java.util.ArrayList{
    [list] elements(
        java.lang.Object element,
    ),
}
```

**Comment by yqbjtu** [comment]
I changed  my export code like the following ,  the export works now. it seems that my original storage data is written with BinaryHandlersJDK8::registerJDK8TypeHandlers 

```
         final EmbeddedStorageManager storage = EmbeddedStorage.Foundation( Paths.get(DATA_DIR))
          .onConnectionFoundation(BinaryHandlersJDK8::registerJDK8TypeHandlers)
          .start();
```

**Comment by yqbjtu** [comment]
if the storage data is from microsteam 8.0, it is like this:
PersistenceTypeDictionary.ptd
0000000000000000043 java.util.ArrayList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000044 java.util.HashSet{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000046 java.util.HashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}

If I modify my PersistenceTypeDictionary.ptd directly  by  making it  like the one generated by microstream 8.0, but the export still fail

===23.931 [main] ERROR o.m.s.e.t.EmbeddedStorageManager$Default.initialize - Exception occurred while initializing embedded storage manager
one.microstream.persistence.binary.exceptions.BinaryPersistenceExceptionInvalidList: Invalid list data: entityLength = 460, objectId = 1000000000000000029, typeId = 46, listStartOffset = 0, listTotalLength = 1856487030784.
	at one.microstream.persistence.binary.types.Binary.getBinaryListTotalByteLength(Binary.java:755)
	at one.microstream.persistence.binary.types.Binary.getBinaryListElementCountValidating(Binary.java:774)
	at one.microstream.persistence.binary.types.Binary.iterateListStructureReferenceRange(Binary.java:877)
	at one.microstream.persistence.binary.types.Binary.iterateKeyValueEntriesReferences(Binary.java:948)

===typeId = 46
in the microstream 7.9.  0000000000000000046 java.util.HashMap{
	float  loadFactor,
	[list] elements  (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}

When I modify type 46 to 
0000000000000000046 java.util.HashMap{
	[list] elements  (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}

my project runs but fail at last for 
15:57:23.931 [main] ERROR o.m.s.e.t.EmbeddedStorageManager$Default.initialize - Exception occurred while initializing embedded storage manager
one.microstream.persistence.binary.exceptions.BinaryPersistenceExceptionInvalidList: Invalid list data: entityLength = 460, objectId = 1000000000000000029, typeId = 46, listStartOffset = 0, listTotalLength = 1856487030784.
	at one.microstream.persistence.binary.types.Binary.getBinaryListTotalByteLength(Binary.java:755)
