### ISSUE TITLE
when calling clear of LazyArrayList, there is an exception "this.loadedSegments" is null

### ISSUE THREAD

**Issue by yqbjtu** [microstream-one/microstream#584]
## Environment Details
* MicroStream Version:8.0
* JDK version:17
* OS:Mac 
* Used springboot 2.6.8

## Describe the bug
I used LazyArrayList to store some data. My dataRoot like this

class DataRoot {
   Map<String, LazyArrayList<Meta>> mapList

}

When some key is not needed, I'll clear the list and store list , remove the key from  mapList and storing mapList.  
## To Reproduce
1,  store 10 keys to mapList
2,  close storage
3,   open storage
4,    clear the list

exception:
2023-05-27 17:23:51,015 ERROR a.m.o.c.base.PListContainer.writeOp [http-nio-80-exec-10] Error while writing value, errMsg:Cannot invoke "java.util.LinkedList.remove(Object)" because "this.loadedSegments" is null
java.lang.NullPointerException: Cannot invoke "java.util.LinkedList.remove(Object)" because "this.loadedSegments" is null
        at one.microstream.collections.lazy.LazySegmentUnloader$Default.remove(LazySegmentUnloader.java:176)
        at one.microstream.collections.lazy.LazyArrayList.clear(LazyArrayList.java:559)

## Expected behavior
The list is cleared and  no exception

**Comment by hg-ms** [comment]
Bug Confirmed.
If clear is called after an LazyArrayList has been loaded from the storage the segment unloader does not check if the internal list of loaded segments is null.
