### ISSUE TITLE
java.lang.ClassNotFoundException: sun.misc.Unsafe

### ISSUE THREAD

**Issue by ts-00** [microstream-one/microstream#618]
## Environment Details
* MicroStream Version: 08.01.01-MS-GA
* JDK version: openjdk version "18.0.2.1" 2022-08-18 (used for project and wildfly server)
* OS: Mac OS
* Used frameworks: Wildfly v. 29.0.0

## Describe the bug

I upgraded Wildfly from version 26 to **version 29** and now I get the following error:

```
Caused by: jakarta.ejb.EJBException: WFLYEJB0442: Unexpected Error
	at org.jboss.as.ejb3@29.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:273)
	at org.jboss.as.ejb3@29.0.0.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:416)
	at org.jboss.as.ejb3@29.0.0.Final//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:68)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld@29.0.0.Final//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@29.0.0.Final//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee@29.0.0.Final//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3@29.0.0.Final//org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@2.0.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee@29.0.0.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at deployment.myapp.war//one.microstream.memory.sun.JdkInternals.getMemoryAccess(JdkInternals.java:84)
	at deployment.myapp.war//one.microstream.memory.sun.JdkInternals.<clinit>(JdkInternals.java:59)
	at deployment.myapp.war//one.microstream.memory.sun.JdkMemoryAccessor.guaranteeUsability(JdkMemoryAccessor.java:57)
	at deployment.myapp.war//one.microstream.memory.XMemory.guaranteeUsability(XMemory.java:365)
	at deployment.myapp.war//one.microstream.persistence.binary.types.Binary.<clinit>(Binary.java:144)
	at deployment.myapp.war//one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustom.chars(AbstractBinaryHandlerCustom.java:96)
	at deployment.myapp.war//one.microstream.persistence.binary.java.lang.BinaryHandlerString.<init>(BinaryHandlerString.java:50)
	at deployment.myapp.war//one.microstream.persistence.binary.java.lang.BinaryHandlerString.New(BinaryHandlerString.java:36)
	at deployment.myapp.war//one.microstream.persistence.binary.types.BinaryPersistence.createNativeHandlersValueTypes(BinaryPersistence.java:229)
	at deployment.myapp.war//one.microstream.persistence.binary.types.BinaryPersistence.createDefaultCustomTypeHandlerRegistry(BinaryPersistence.java:168)
	at deployment.myapp.war//one.microstream.persistence.binary.types.BinaryPersistenceFoundation$Default.lambda$ensureCustomTypeHandlerRegistryEnsurer$1(BinaryPersistenceFoundation.java:249)
	at deployment.myapp.war//one.microstream.persistence.binary.types.BinaryPersistenceFoundation$Default.ensureCustomTypeHandlerRegistry(BinaryPersistenceFoundation.java:261)
	at deployment.myapp.war//one.microstream.persistence.types.PersistenceFoundation$Default.getCustomTypeHandlerRegistry(PersistenceFoundation.java:985)
	at deployment.myapp.war//one.microstream.persistence.types.PersistenceFoundation$Default.ensureRootsProvider(PersistenceFoundation.java:2475)
	at deployment.myapp.war//one.microstream.persistence.types.PersistenceFoundation$Default.getRootsProvider(PersistenceFoundation.java:1350)
	at deployment.myapp.war//one.microstream.storage.embedded.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:799)
	at deployment.myapp.war//one.microstream.storage.embedded.types.EmbeddedStorageFoundation.start(EmbeddedStorageFoundation.java:240)
	at deployment.myapp.war//one.microstream.storage.embedded.types.EmbeddedStorageFoundation.start(EmbeddedStorageFoundation.java:209)
...
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe from [Module "deployment.myapp.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 78 more
```

The VM argument when starting the server already includes

```
.. 
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED 
--add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED 
..
```

## To Reproduce
Use Wildfly v. 29.0.0 with MicroStream v: 08.01.01-MS-GA and start an `EmbeddedStorageManager` on a method declared within a `@Startup`-bean.

## Additional context
The direct use of `sun/misc/Unsafe` for 3rd party libs seems to be unsafe. Maybe microstream can replace its use of`sun/misc/Unsafe` by alternatives described in http://www.angelikalanger.com/Articles/EffectiveJava/91.Java9.What-is-new-in-Java-9/90.java-9.1.overview.ready_7.html to have a more future proof solution.

To resolve this issue, maybe it is possible to refactor the code to remove the dependency on `sun.misc.Unsafe`. It's recommended to find alternative ways or standard Java APIs to accomplish the task without relying on internal APIs.

Relying on internal APIs can lead to compatibility issues and unexpected behavior, as they are not meant for general use and may not be available in all Java implementations.

**Comment by ts-00** [comment]
I looked in the jdk directory and see that there is really not such package `sun.misc.Unsafe` but there is a `jdk.internal.misc.Unsafe`. Looking at 

`one.microstream.memory.sun.JdkInternals.getMemoryAccess(JdkInternals.java:84)`

it uses the outdated `sun.misc.Unsafe` instead of `jdk.internal.misc.Unsafe`. 

But I already use **MicroStream Version: 08.01.01-MS-GA** and according to the [docs](https://docs.microstream.one/manual/intro/system-requirements.html), it is compatible to OpenJDK18.

**Comment by hg-ms** [comment]
Microstream is compatible with java 18. The package sun.misc is imported using the jdk.unsupported module that exports sun.misc. I’d assume that Wildfly does not provide the jdk.unsupported module by default.

**Comment by ts-00** [comment]
>. I’d assume that Wildfly does not provide the jdk.unsupported module by default.

Yes, that's a good assumption. Looking into 

`wildfly/modules/system/layers/base/sun/jdk/main `

there is the following `module.xml `which is now market as **deprecated**:

_snippet:_
```
<?xml version="1.0" encoding="UTF-8"?>
<module name="sun.jdk" xmlns="urn:jboss:module:1.6">
	<!--
		This module is deprecated and any use of it should be replaced
		with the use of a JPMS module provided by Java SE.
		
		The original purpose of this module was to make it possible for
		JBoss Modules modules to get access to various Java SE packages.
		However, since Java SE 9, Java SE has exposed these packages via
		SE's own JPMS modules, and JBoss Modules allows modules to declare
		dependencies on SE's JPMS modules in the same way dependencies
		on native JBoss Modules modules are declared. Simply use the name
		of the JPMS module in a 'module' element's 'name' attribute. 
		
		For example, to add a dependency on the Java SE jdk.security.jgss module:
		
		<module name="jdk.security.jgss"/>
		
		In the 'paths' section below, the various resource paths (i.e. packages)
		exposed by this module are grouped by the JPMS module that provides
		them, with a comment identifying the relevant JPMS module. Users
		moving away from use of this module can use this information to 
		identify the appropriate JPMS module(s) to use instead of this one.
	-->	
    <properties>
        <property name="jboss.api" value="deprecated"/>
    </properties>

    <resources>
        <!-- currently jboss modules has not way of importing services from
        classes.jar so we duplicate them here -->
        <resource-root path="service-loader-resources"/>
    </resources>
    <dependencies>
        <module name="sun.scripting" export="true"/>
        <system export="true">
            <paths>
                <!-- See below for replacement modules -->
              ...
                <!-- Module jdk.unsupported -->

                <path name="sun/misc"/>
              ...
            </paths>
            <exports>
                <include-set>
                    <path name="META-INF/services"/>
                </include-set>
            </exports>
        </system>
    </dependencies>
</module>
```

According to the text

> This module is deprecated and any use of it should be replaced with the use of a JPMS module provided by Java SE.

I should use JPMS. Does that mean I do not need a `jdk.unsupported` module when using JPMS? I added 

`--add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED`

within the Wildfly-"VM Arguments ", but the same error as above occurs.

So how can I use JPMS (as wildfly suggests) to solve this issue?

**Comment by ts-00** [comment]
@hg-ms The solution is simply by adding 

```
<dependencies>
    <module name="jdk.unsupported" />
</dependencies>
```

within `jboss:deployment-structure.xml`.
