### ISSUE TITLE
Getting Exception in thread "main" one.microstream.persistence.exceptions.PersistenceExceptionImproperObjectId

### ISSUE THREAD

**Issue by notsharable** [microstream-one/microstream#7]
Hi,

when executing the following  
	public static void withCodeConfig() {
		DataRoot root = new DataRoot();	

		final EmbeddedStorageManager storageManager = Configuration.Default()
			    .setBaseDirectoryInUserHome("data-dir")
			    .setBackupDirectory("backup-dir")
			    .setChannelCount(4)
			    .createEmbeddedStorageFoundation()
			    //.start(root);
			    //.setRoot(root)
				.createEmbeddedStorageManager();
		root.setContent("Hello World @!"+new Date());		
		storageManager.setRoot(root);
		storageManager.start();
		storageManager.storeRoot();
		storageManager.shutdown();
	}

... I a encountering this problem
Exception in thread "main" one.microstream.persistence.exceptions.PersistenceExceptionImproperObjectId
	at one.microstream.persistence.internal.DefaultObjectRegistry.registerObject(DefaultObjectRegistry.java:464)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.registerRoot(BinaryLoader.java:352)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.requireRoot(BinaryLoader.java:326)
	at one.microstream.persistence.types.BinaryHandlerRootReferenceDefault.create(BinaryHandlerRootReferenceDefault.java:111)
	at one.microstream.persistence.types.BinaryHandlerRootReferenceDefault.create(BinaryHandlerRootReferenceDefault.java:1)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustom.create(AbstractBinaryHandlerCustom.java:1)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:201)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:154)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:142)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:266)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:275)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:801)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:771)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOnce(BinaryLoader.java:713)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.get(BinaryLoader.java:824)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.loadRoots(BinaryLoader.java:869)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.loadExistingRoots(EmbeddedStorageManager.java:306)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.initialize(EmbeddedStorageManager.java:326)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:214)
	at one.microstream.storage.types.EmbeddedStorageManager$Default.start(EmbeddedStorageManager.java:1)
	at org.dnd.datastore.DataRootApp.withCodeConfig(DataRootApp.java:64)
	at org.dnd.datastore.DataRootApp.main(DataRootApp.java:17)

I have tried to to call start() in various order but it didn't help. 

Does anyone has some idea of what might be going wrong and how to solve it?

I am just starting exploring Microstream.
Thanks.

**Comment by hg-ms** [comment]
Hello,
The exception is caused by an invalid ObjectId (a value <= 0 is read but should be > 0) read from the storage during startup. Why this happens is hard to say without additional details. Maybe there was already an old storage from earlier experiments? 

Can you reproduce the error if you re-create the storage into new (empty) directories?
(To delete a storage just delete the related directories from the filesystem).

Some additional note on the order of the calls:
1.	start()
This will either create a new storage or load an existing one.
2.	root()
Will return the loaded root node or null in case of an empty storage.
3.	setRoot(...)
This will set a new root node. If a root has already been set it will be replaced. Be careful as this may whipe the whole storage.
4.	storeRoot()
will store the root node

**Comment by notsharable** [comment]
Thanks hg-ms for the hints and clarifications.

There was indeed a stale data  directory named "storage" I do not recall having created that as my initial experiment was the "Hello World @!"  using Paths.get("data") to specify data directory.

After removing the directory the problem was gone.

Thanks
