### ISSUE TITLE
Android - PersistenceExceptionTypeConsistency

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#83]
Save and reload from Repository fail on Android with following message:

```
one.microstream.persistence.exceptions.PersistenceExceptionTypeConsistency: TypeId inconsistency for one.microstream.persistence.types.PersistenceRoots$Default: typeDictionary type definition typeId = 1000047, validated type handler typeId = 1000061

E/TestRunner: failed: saveAndLoadTest()(BasicNonPrimitiveTypesTests)

E/TestRunner: one.microstream.persistence.exceptions.PersistenceExceptionTypeConsistency: TypeId inconsistency for one.microstream.persistence.types.PersistenceRoots$Default: typeDictionary type definition typeId = 1000047, validated type handler typeId = 1000061
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.validateTypeHandler(PersistenceTypeHandlerManager.java:284)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandler(PersistenceTypeHandlerManager.java:555)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.internalEnsureTypeHandler(PersistenceTypeHandlerManager.java:543)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:351)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeId(PersistenceTypeHandlerManager.java:752)
        at one.microstream.storage.types.EmbeddedStorageRootTypeIdProvider$Default.initialize(EmbeddedStorageRootTypeIdProvider.java:61)
        at one.microstream.storage.types.EmbeddedStorageFoundation$Default.initializeEmbeddedStorageRootTypeIdProvider(EmbeddedStorageFoundation.java:659)
        at one.microstream.storage.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:739)
        at one.microstream.storage.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:586)
        at one.microstream.storage.types.EmbeddedStorage.start(EmbeddedStorage.java:472)
        at one.microstream.AbstractHandlerTest.startStorage(AbstractHandlerTest.java:164)
        at one.microstream.AbstractHandlerTest.saveToMSAndReload(AbstractHandlerTest.java:151)
        at one.microstream.AbstractHandlerTest.saveAndLoadTest(AbstractHandlerTest.java:66)
        at one.microstream.BasicNonPrimitiveTypesTests.saveAndLoadTest(BasicNonPrimitiveTypesTests.java:17)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6$TestMethodTestDescriptor(TestMethodTestDescriptor.java:171)
        at org.junit.jupiter.engine.descriptor.-$$Lambda$TestMethodTestDescriptor$eOXpdJL9axLS-As6h-8JcXoSDRw.execute(Unknown Source:6)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4$NodeTestTask(NodeTestTask.java:108)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$E0p9vUaH16T2ejXiuK-ilqxbgAw.execute(Unknown Source:2)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$YtR87xxv7Lsk5lq-Q1zNp0wlLKE.accept(Unknown Source:2)
        at java.util.ArrayList.forEach(ArrayList.java:1262)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4$NodeTestTask(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$E0p9vUaH16T2ejXiuK-ilqxbgAw.execute(Unknown Source:2)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(Throw

```

**Comment by tm-ms** [comment]
The same error occurs in a client project from CK when updating from 2.0 to 2.3.
Updating to 2.2 does not produce the exception.

Weird that all other tests (including my own when development-testing) do not have that problem.

**Comment by tm-ms** [comment]
Thanks to HG, the cause for this problem has been found in CK's customer project.

Since microstream-one/microstream-public#78, the class loader used to try to resolve classes is configurable, but by default `ClassLoader.getSystemClassLoader();`. Before, `Class#forName` was used, which internally uses the current context's class loader.
The default behavior was changed in the assumption that the system class loader is the one that initialized the storage and therefore has all the right Class instances.
It turned out that this assumption was wrong.

It seems that in the customer project, the "other" ClassLoader, provided by the application server context, does all the initialization. If then the type lookup uses the System ClassLoader, the type name resolving produces a different Class instance for the same type, resulting in the exception above.

Specifically:
Changing the ClassLoader dfault providing logic in ClassLoaderProvider from
`return ClassLoader.getSystemClassLoader();`
to
`return ClassLoaderProvider.class.getClassLoader();`
fixes the problem (as it basically reverts the switch to the system class loader back to the context class loader)

The first one is:
```
sun.misc.Launcher$AppClassLoader
```
The second one is:
```
ParallelWebappClassLoader
  context: tmc_kis
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@62ee68d8
```

This means microstream-one/microstream-public#78 needs to be reopened and its ClassLoader default strategy be changed.

**Comment by hg-ms** [comment]
after changes for microstream-one/microstream-public#78:

ZJ did a short test on Android using the current head 935ab52f from 9. March 2020 on Android
The PersistenceExceptionTypeConsistency seem to be resolved there.
