### ISSUE TITLE
Cache - Spring @Cacheble method annotation support

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#91]
In Spring i have a possibility to add annotation for method in Bean. 
e.g.
```
package one.microstream.service;

import one.microstream.data.Employee;
import one.microstream.repository.EmployeeRepository;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class EmployeeServiceImpl implements EmployeeService {

    @Autowired
    EmployeeRepository employeeRepository;

    @Override
    @Cacheable("Employees")
    public List<Employee> findAll() {
        return (List<Employee>) employeeRepository.findAll();
    }
}
```
This is very usefull, when some methods is expensive and i don't need acutal data. 
https://www.baeldung.com/spring-cache-tutorial

Reference doku Spring:
https://docs.spring.io/spring/docs/4.3.15.RELEASE/spring-framework-reference/html/cache.html
actual:
https://docs.spring.io/spring/docs/5.2.4.RELEASE/spring-framework-reference/integration.html#cache

Log:
```
Caused by: java.lang.IllegalArgumentException: Cannot find cache named 'Employees' for Builder[public java.util.List one.microstream.service.EmployeeServiceImpl.findAll()] caches=[Employees] | key='' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
	at org.springframework.cache.interceptor.AbstractCacheResolver.resolveCaches(AbstractCacheResolver.java:92) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.getCaches(CacheAspectSupport.java:252) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContext.<init>(CacheAspectSupport.java:707) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.getOperationContext(CacheAspectSupport.java:265) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport$CacheOperationContexts.<init>(CacheAspectSupport.java:598) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at one.microstream.service.EmployeeServiceImpl$$EnhancerBySpringCGLIB$$d22529e1.findAll(<generated>) ~[classes/:na]
	at one.microstream.DemoApplication.lambda$demo$0(DemoApplication.java:30) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	... 5 common frames omitted

```

**Comment by fh-ms** [comment]
https://docs.spring.io/spring/docs/5.2.4.RELEASE/spring-framework-reference/integration.html#cache-plug

**Comment by zdenek-jonas** [comment]
Ok, diese funktioniert out of the box, we have to create class with cache configuration. E.b.

```
package one.microstream;

import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.stereotype.Component;

import javax.cache.CacheManager;
import javax.cache.configuration.MutableConfiguration;
import javax.cache.expiry.CreatedExpiryPolicy;
import javax.cache.expiry.Duration;

import static java.util.concurrent.TimeUnit.SECONDS;

@Component
public class CachingSetup implements JCacheManagerCustomizer {

    @Override
    public void customize(CacheManager cacheManager) {
        cacheManager.createCache("employee_cache", new MutableConfiguration<>()
                .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(new Duration(SECONDS, 10000)))
                .setStoreByValue(true)
                .setStatisticsEnabled(true));
    }
}

```

**Comment by zdenek-jonas** [comment]
this works... Now i am satistified with this functionality. Maybe future we can create this cache automatically ...
