### ISSUE TITLE
Android - PersistenceExceptionTypeConsistency

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#93]
Legacy type mapping Android:
I save this first class, ByteLegacy. Then I start to load this file with ByteLegacy2 and receive the following Exception.

This problem happens by any test what i have for Android. 

```
public class ByteLegacy {

    private byte byteTo_float;
    private byte byteTo_double;
    private byte byteTo_short;
    private byte byteTo_long;
    private byte byteTo_byte;
    private byte byteTo_int;
    private byte byteToString;
    private byte byteTo_boolean;
    private byte byteTo_char;
    private byte byteToByte;
    private Byte copyByteTo_byte;


    public static ByteLegacy fillSample() {
        ByteLegacy legacy = new ByteLegacy();

        legacy.byteTo_float = '1';
        legacy.byteTo_double = '2';
        legacy.byteTo_short = '3';
        legacy.byteTo_long = '4';
        legacy.byteTo_byte = 'a';
        legacy.byteTo_int = '6';
        legacy.byteToString = '5';
        legacy.byteTo_boolean = '0';
        legacy.byteTo_char = 'c';
        legacy.byteToByte = 'x';
        legacy.copyByteTo_byte = 'i';
        return legacy;
    }
}

public class ByteLegacy2 {

    private float byteTo_float;
    private double byteTo_double;
    private short byteTo_short;
    private long byteTo_long;
    private byte byteTo_byte;
    private int byteTo_int;
    private char byteToString;
    private boolean byteTo_boolean;
    private char byteTo_char;
    private Byte bytToByte;
    private byte copyByteTo_byte;
}
```

```
E/TestRunner: failed: crossByteLegacyTest()(CrossByteLegacyTest)
E/TestRunner: ----- begin exception -----
E/TestRunner: one.microstream.persistence.exceptions.PersistenceExceptionTypeConsistency: TypeId inconsistency for one.microstream.persistence.types.PersistenceRoots$Default: typeDictionary type definition typeId = 1000044, validated type handler typeId = 1000057
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.validateTypeHandler(PersistenceTypeHandlerManager.java:284)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.registerTypeHandler(PersistenceTypeHandlerManager.java:555)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.internalEnsureTypeHandler(PersistenceTypeHandlerManager.java:543)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeHandler(PersistenceTypeHandlerManager.java:351)
        at one.microstream.persistence.types.PersistenceTypeHandlerManager$Default.ensureTypeId(PersistenceTypeHandlerManager.java:752)
        at one.microstream.storage.types.EmbeddedStorageRootTypeIdProvider$Default.initialize(EmbeddedStorageRootTypeIdProvider.java:61)
        at one.microstream.storage.types.EmbeddedStorageFoundation$Default.initializeEmbeddedStorageRootTypeIdProvider(EmbeddedStorageFoundation.java:659)
        at one.microstream.storage.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:739)
        at one.microstream.storage.types.EmbeddedStorageFoundation.start(EmbeddedStorageFoundation.java:199)
        at one.microstream.storage.types.EmbeddedStorageFoundation.start(EmbeddedStorageFoundation.java:168)
        at one.microstream.legacy.cross.AbstractLegacyTest.startStorage(AbstractLegacyTest.java:21)
        at one.microstream.legacy.cross.CrossByteLegacyTest.crossByteLegacyTest(CrossByteLegacyTest.java:26)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6$TestMethodTestDescriptor(TestMethodTestDescriptor.java:171)
        at org.junit.jupiter.engine.descriptor.-$$Lambda$TestMethodTestDescriptor$eOXpdJL9axLS-As6h-8JcXoSDRw.execute(Unknown Source:6)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4$NodeTestTask(NodeTestTask.java:108)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$E0p9vUaH16T2ejXiuK-ilqxbgAw.execute(Unknown Source:2)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$YtR87xxv7Lsk5lq-Q1zNp0wlLKE.accept(Unknown Source:2)
        at java.util.ArrayList.forEach(ArrayList.java:1262)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4$NodeTestTask(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$E0p9vUaH16T2ejXiuK-ilqxbgAw.execute(Unknown Source:2)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
    	at org.junit.pla
    ----- end exception -----

```

```
0000000000000000001 byte{
	primitive 8 bit integer signed,
}
0000000000000000002 boolean{
	primitive 8 bit boolean,
}
0000000000000000003 short{
	primitive 16 bit integer signed,
}
0000000000000000004 char{
	primitive 16 bit integer unicode,
}
0000000000000000005 int{
	primitive 32 bit integer signed,
}
0000000000000000006 float{
	primitive 32 bit decimal IEEE754,
}
0000000000000000007 long{
	primitive 64 bit integer signed,
}
0000000000000000008 double{
	primitive 64 bit decimal IEEE754,
}
0000000000000000010 java.lang.Object{}
0000000000000000011 java.lang.Byte{
	byte value,
}
0000000000000000012 java.lang.Boolean{
	boolean value,
}
0000000000000000013 java.lang.Short{
	short value,
}
0000000000000000014 java.lang.Character{
	char value,
}
0000000000000000015 java.lang.Integer{
	int value,
}
0000000000000000016 java.lang.Float{
	float value,
}
0000000000000000017 java.lang.Long{
	long value,
}
0000000000000000018 java.lang.Double{
	double value,
}
0000000000000000019 java.lang.Void{}
0000000000000000020 java.lang.Class{
	long value,
}
0000000000000000030 java.lang.String{
	[char] value,
}
0000000000000000032 java.lang.StringBuffer{
	long   capacity,
	[char] value   ,
}
0000000000000000033 java.lang.StringBuilder{
	long   capacity,
	[char] value   ,
}
0000000000000000034 java.io.File{
	[char] path,
}
0000000000000000035 java.util.Date{
	long timestamp,
}
0000000000000000037 java.math.BigInteger{
	[byte] value,
}
0000000000000000038 java.math.BigDecimal{
	[char] value,
}
0000000000000000043 java.util.ArrayList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000044 java.util.HashSet{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000046 java.util.HashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000048 java.util.Hashtable{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000049 java.util.ArrayDeque{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000050 java.util.IdentityHashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000051 java.util.LinkedHashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000052 java.util.LinkedHashSet{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000054 java.util.LinkedList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000056 java.util.PriorityQueue{
	java.util.Comparator comparator,
	[list]               elements  (
		java.lang.Object element,
	),
}
0000000000000000057 java.util.TreeMap{
	java.util.Comparator comparator,
	[list]               elements  (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000058 java.util.TreeSet{
	java.util.Comparator comparator,
	[list]               elements  (
		java.lang.Object element,
	),
}
0000000000000000059 java.util.Vector{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000060 java.util.Stack{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000061 java.util.Properties{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000062 java.util.concurrent.ConcurrentHashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000063 java.util.concurrent.ConcurrentLinkedDeque{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000064 java.util.concurrent.ConcurrentLinkedQueue{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000000065 java.util.concurrent.ConcurrentSkipListMap{
	java.util.Comparator comparator,
	[list]               elements  (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000000000066 java.util.concurrent.ConcurrentSkipListSet{
	java.util.Comparator comparator,
	[list]               elements  (
		java.lang.Object element,
	),
}
0000000000000000068 java.util.Locale{
	[char] languageTag,
}
0000000000000000101 [B{
	[list] elements(
		byte element,
	),
}
0000000000000000102 [Z{
	[list] elements(
		boolean element,
	),
}
0000000000000000103 [S{
	[list] elements(
		short element,
	),
}
0000000000000000104 [C{
	[list] elements(
		char element,
	),
}
0000000000000000105 [I{
	[list] elements(
		int element,
	),
}
0000000000000000106 [F{
	[list] elements(
		float element,
	),
}
0000000000000000107 [J{
	[list] elements(
		long element,
	),
}
0000000000000000108 [D{
	[list] elements(
		double element,
	),
}
0000000000000000110 [Ljava.lang.Object;{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000000010000 one.microstream.reference.Lazy$Default{
	java.lang.Object subject,
}
0000000000001000001 java.sql.Date{
	long timestamp,
}
0000000000001000002 java.util.OptionalInt{
	boolean isPresent,
	int     value    ,
}
0000000000001000003 java.util.OptionalLong{
	boolean isPresent,
	long    value    ,
}
0000000000001000004 java.util.OptionalDouble{
	boolean isPresent,
	double  value    ,
}
0000000000001000005 java.util.Collections$UnmodifiableNavigableSet$EmptyNavigableSet{}
0000000000001000010 java.util.Collections$UnmodifiableNavigableMap$EmptyNavigableMap{}
0000000000001000014 java.util.Collections$ReverseComparator{}
0000000000001000015 java.util.WeakHashMap{
	[list] elements(
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000001000016 java.util.concurrent.CopyOnWriteArrayList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000001000017 java.util.Comparators$NaturalOrderComparator{
	enum INSTANCE,
}
0000000000001000018 java.util.Optional{
	java.lang.Object java.util.Optional#value,
}
0000000000001000019 one.microstream.collections.BulkList{
	long   capacity,
	[list] elements(
		java.lang.Object element,
	),
}
0000000000001000024 one.microstream.collections.LimitList{
	long   capacity,
	[list] elements(
		java.lang.Object element,
	),
}
0000000000001000025 one.microstream.collections.FixedList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000001000026 one.microstream.collections.ConstList{
	[list] elements(
		java.lang.Object element,
	),
}
0000000000001000027 one.microstream.collections.EqBulkList{
	one.microstream.hashing.HashEqualator hashEqualator,
	long                                  capacity     ,
	[list]                                elements     (
		java.lang.Object element,
	),
}
0000000000001000028 one.microstream.collections.HashEnum{
	float  hashDensity,
	[list] elements   (
		java.lang.Object element,
	),
}
0000000000001000030 one.microstream.collections.ConstHashEnum{
	float  hashDensity,
	[list] elements   (
		java.lang.Object element,
	),
}
0000000000001000031 one.microstream.collections.EqHashEnum{
	one.microstream.hashing.HashEqualator hashEqualator,
	float                                 hashDensity  ,
	[list]                                elements     (
		java.lang.Object element,
	),
}
0000000000001000032 one.microstream.collections.EqConstHashEnum{
	one.microstream.hashing.HashEqualator hashEqualator,
	float                                 hashDensity  ,
	[list]                                elements     (
		java.lang.Object element,
	),
}
0000000000001000033 one.microstream.collections.HashTable{
	one.microstream.collections.HashTable$Keys   keys       ,
	one.microstream.collections.HashTable$Values values     ,
	float                                        hashDensity,
	[list]                                       elements   (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000001000035 one.microstream.collections.ConstHashTable{
	one.microstream.collections.ConstHashTable$Keys   keys       ,
	one.microstream.collections.ConstHashTable$Values values     ,
	float                                             hashDensity,
	[list]                                            elements   (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000001000036 one.microstream.collections.EqHashTable{
	one.microstream.hashing.HashEqualator          hashEqualator,
	one.microstream.collections.EqHashTable$Keys   keys         ,
	one.microstream.collections.EqHashTable$Values values       ,
	float                                          hashDensity  ,
	[list]                                         elements     (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000001000037 one.microstream.collections.EqConstHashTable{
	one.microstream.hashing.HashEqualator               hashEqualator,
	one.microstream.collections.EqConstHashTable$Keys   keys         ,
	one.microstream.collections.EqConstHashTable$Values values       ,
	float                                               hashDensity  ,
	[list]                                              elements     (
		java.lang.Object key  ,
		java.lang.Object value,
	),
}
0000000000001000038 one.microstream.collections.Singleton{
	java.lang.Object element,
}
0000000000001000039 one.microstream.util.Substituter$Default{
	one.microstream.hashing.HashEqualator hashEqualator,
	float                                 hashDensity  ,
	[list]                                elements     (
		java.lang.Object element,
	),
}
0000000000001000040 one.microstream.persistence.types.PersistenceRoots$Default{
	[list] instances  (
		java.lang.Object instance,
	),
	[list] identifiers(
		[char] identifier,
	),
}
0000000000001000041 one.microstream.persistence.types.PersistenceRootReference$Default{
	java.lang.Object root,
}
0000000000001000042 one.microstream.hashing.XHashing$SingletonValueHashEqualator{}
0000000000001000043 one.microstream.hashing.XHashing$SingletonIdentityHashEqualator{}
0000000000001000044 one.microstream.hashing.XHashing$SingletonKeyValueIdentityHashEqualator{}
0000000000001000045 one.microstream.collections.Empty{}
0000000000001000046 one.microstream.collections.EmptyTable{
	one.microstream.collections.EmptyTable$Keys   one.microstream.collections.EmptyTable#keys  ,
	one.microstream.collections.EmptyTable$Values one.microstream.collections.EmptyTable#values,
}
0000000000001000047 one.microstream.collections.EmptyTable$Keys{
	one.microstream.collections.EmptyTable one.microstream.collections.EmptyTable$Keys#this$0,
}
0000000000001000048 one.microstream.collections.EmptyTable$Values{
	one.microstream.collections.EmptyTable one.microstream.collections.EmptyTable$Values#this$0,
}
0000000000001000049 java.util.Collections$EmptyList{}
0000000000001000050 java.util.Collections$EmptySet{}
0000000000001000051 java.util.Collections$EmptyMap{}
0000000000001000052 test.microstream.configuration.Customer{
	java.lang.String test.microstream.configuration.Customer#firstName ,
	java.lang.String test.microstream.configuration.Customer#secondName,
	java.lang.String test.microstream.configuration.Customer#street    ,
	java.lang.String test.microstream.configuration.Customer#city      ,
}

```

**Comment by zdenek-jonas** [comment]
I close this bug. The reason for this bug is, that Android Studio and Gradle plugin does not update snapshots, although the one direct this functionality call. 
It is necessary to call direct from command line.
```
gradlew app:assemble app:assembleAndroidTest build -x lint  --refresh-dependencies
```
