### ISSUE TITLE
REST-Service API-Layer - ClassType - Error 500

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#96]
![screen](https://user-images.githubusercontent.com/17253582/78011461-e9c18b80-7343-11ea-9654-114576ab4f40.png)
When i store a Class with Class member, i received 500 error.

```
    class ClassType  {
        Class clazz;

        public void fillSampleData() {
            clazz = PrimitiveTypes.class;
        }

        Class getClazz() {
            return clazz;
        }
    }
```

```
javax.ws.rs.InternalServerErrorException: HTTP 500 Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1081) ~[jersey-client-2.29.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:866) ~[jersey-client-2.29.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:750) ~[jersey-client-2.29.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.29.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.29.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[jersey-common-2.29.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390) ~[jersey-common-2.29.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:748) ~[jersey-client-2.29.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404) ~[jersey-client-2.29.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300) ~[jersey-client-2.29.1.jar:na]
	at one.microstream.storage.restclient.types.StorageRestClientJersey.requestObject(StorageRestClientJersey.java:119) ~[classes/:na]
	at one.microstream.storage.restclient.types.StorageView$Default.members(StorageView.java:74) ~[classes/:na]
	at one.microstream.storage.restclient.types.StorageViewObject$Complex.members(StorageViewObject.java:85) ~[classes/:na]
	at one.microstream.storage.restclient.ui.StorageViewDataProvider$Default.getChildCount(StorageViewDataProvider.java:61) ~[classes/:na]
	at com.vaadin.flow.data.provider.hierarchy.HierarchyMapper.countChildItems(HierarchyMapper.java:354) ~[flow-data-2.1.6.jar:2.1.6]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalCommunicationController.flush(HierarchicalCommunicationController.java:116) ~[flow-data-2.1.6.jar:2.1.6]
	at com.vaadin.flow.data.provider.hierarchy.HierarchicalDataCommunicator.lambda$requestFlush$e15592a2$1(HierarchicalDataCommunicator.java:137) ~[flow-data-2.1.6.jar:2.1.6]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368) ~[flow-server-2.1.6.jar:2.1.6]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_221]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:411) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:187) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:121) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) [flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:96) [vaadin-spring-12.1.3.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
```

Server log:
```
one.microstream.exceptions.NumberRangeException
	at one.microstream.math.XMath.positive(XMath.java:1391)
	at one.microstream.persistence.binary.types.Binary.validateLoadItemContentLength(Binary.java:1934)
	at one.microstream.persistence.binary.types.Binary.update_chars(Binary.java:2114)
	at one.microstream.java.lang.BinaryHandlerNativeArray_char.updateState(BinaryHandlerNativeArray_char.java:50)
	at one.microstream.java.lang.BinaryHandlerNativeArray_char.updateState(BinaryHandlerNativeArray_char.java:1)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerNativeArray.create(ViewerBinaryTypeHandlerNativeArray.java:32)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerNativeArray.create(ViewerBinaryTypeHandlerNativeArray.java:1)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:196)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:148)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:136)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:266)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:275)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:788)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:758)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:823)
	at one.microstream.storage.restadapter.ViewerBinaryPersistenceManager.getStorageObject(ViewerBinaryPersistenceManager.java:216)
	at one.microstream.storage.restadapter.EmbeddedStorageRestAdapter.getStorageObject(EmbeddedStorageRestAdapter.java:56)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReference(ObjectDescription.java:190)
	at one.microstream.storage.restadapter.ObjectDescription.lambda$2(ObjectDescription.java:149)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReferences(ObjectDescription.java:150)
	at one.microstream.storage.restadapter.StorageRestAdapter$Default.getObject(StorageRestAdapter.java:72)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:36)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:1)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zdenek-jonas** [comment]
Unfortunately, this produces now another backend Exception:
```
[qtp352699136-19] ERROR spark.http.matching.GeneralError - 
java.lang.UnsupportedOperationException
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerGeneric.typeName(ViewerBinaryTypeHandlerGeneric.java:54)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerManager.lambda$1(ViewerBinaryTypeHandlerManager.java:178)
	at one.microstream.collections.ChainStrongStrongStorage.valuesSearch(ChainStrongStrongStorage.java:3148)
	at one.microstream.collections.EqHashTable$Values.search(EqHashTable.java:3621)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerManager.lookupTypeHandler(ViewerBinaryTypeHandlerManager.java:177)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerManager.ensureTypeHandler(ViewerBinaryTypeHandlerManager.java:197)
	at one.microstream.java.lang.BinaryHandlerClass.instanceState(BinaryHandlerClass.java:65)
	at one.microstream.java.lang.BinaryHandlerClass.validateState(BinaryHandlerClass.java:132)
	at one.microstream.java.lang.BinaryHandlerClass.validateState(BinaryHandlerClass.java:1)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.updateState(AbstractBinaryHandlerCustomValue.java:57)
	at one.microstream.persistence.binary.internal.AbstractBinaryHandlerCustomValue.updateState(AbstractBinaryHandlerCustomValue.java:1)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerBasic.updateState(ViewerBinaryTypeHandlerBasic.java:36)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerWrapperAbstract.updateState(ViewerBinaryTypeHandlerWrapperAbstract.java:1)
	at one.microstream.persistence.types.PersistenceTypeHandler.initializeState(PersistenceTypeHandler.java:47)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.buildInstances(BinaryLoader.java:443)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.build(BinaryLoader.java:382)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:824)
	at one.microstream.storage.restadapter.ViewerBinaryPersistenceManager.getStorageObject(ViewerBinaryPersistenceManager.java:245)
	at one.microstream.storage.restadapter.EmbeddedStorageRestAdapter.getStorageObject(EmbeddedStorageRestAdapter.java:56)
	at one.microstream.storage.restadapter.StorageRestAdapter$Default.getObject(StorageRestAdapter.java:69)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:36)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:1)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
...
```

With exactly these classes:
```
static class ClassType {
    Class clazz;
    public void fillSampleData() {
        clazz = PrimitiveTypes.class;
    }
    Class getClazz() {
        return clazz;
    }
}
```
```
public class PrimitiveTypes {
    private static final byte SAMPLE_BYTE = 100;
    private static final short SAMPLE_SHORT = 50;
    private static final int SAMPLE_INT = 5401;
    private static final long SAMPLE_LONG = 1545455464654L;
    private static final float SAMPLE_FLOAT = 3.141526f;
    private static final double SAMPLE_DOUBLE = 3.141526545;
    private static final boolean SAMPLE_BOOLEAN = Boolean.TRUE;
    private static final char SAMPLE_CHAR = 'c';

    private byte byteValue;
    private short shortValue;
    private int intValue;
    private long longValue;
    private float floatValue;
    private double doubleValue;
    private boolean booleanValue;
    private char charValue;
    public PrimitiveTypes() {
        super();
    }
    public static PrimitiveTypes fillSample() {
        PrimitiveTypes p = new PrimitiveTypes();
        p.fillSampleData();
        return p;
    }
    public void fillSampleData() {
        this.byteValue = SAMPLE_BYTE;
        this.shortValue = SAMPLE_SHORT;
        this.intValue = SAMPLE_INT;
        this.longValue = SAMPLE_LONG;
        this.floatValue = SAMPLE_FLOAT;
        this.doubleValue = SAMPLE_DOUBLE;
        this.booleanValue = SAMPLE_BOOLEAN;
        this.charValue = SAMPLE_CHAR;
    }
    public byte getByteValue() {
        return byteValue;
    }
    public short getShortValue() {
        return shortValue;
    }
    public int getIntValue() {
        return intValue;
    }
    public long getLongValue() {
        return longValue;
    }
    public float getFloatValue() {
        return floatValue;
    }
    public double getDoubleValue() {
        return doubleValue;
    }
    public boolean isBooleanValue() {
        return booleanValue;
    }
    public char getCharValue() {
        return charValue;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (booleanValue ? 1231 : 1237);
        result = prime * result + byteValue;
        result = prime * result + charValue;
        long temp;
        temp = Double.doubleToLongBits(doubleValue);
        result = prime * result + (int) (temp ^ (temp >>> 32));
        result = prime * result + Float.floatToIntBits(floatValue);
        result = prime * result + intValue;
        result = prime * result + (int) (longValue ^ (longValue >>> 32));
        result = prime * result + shortValue;
        return result;
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PrimitiveTypes other = (PrimitiveTypes) obj;
        if (booleanValue != other.booleanValue)
            return false;
        if (byteValue != other.byteValue)
            return false;
        if (charValue != other.charValue)
            return false;
        if (Double.doubleToLongBits(doubleValue) != Double.doubleToLongBits(other.doubleValue))
            return false;
        if (Float.floatToIntBits(floatValue) != Float.floatToIntBits(other.floatValue))
            return false;
        if (intValue != other.intValue)
            return false;
        if (longValue != other.longValue)
            return false;
        return shortValue == other.shortValue;
    }

}
```

**Comment by hg-ms** [comment]
Implemented methods typeId() and typeName() in ViewerBinaryTypeHandlerGeneric instead of throwing a UnsupportedOperationException.

**Comment by zdenek-jonas** [comment]
Retest OK
