### ISSUE TITLE
REST-Service API-Layer Primitive Types Array - one.microstream.exceptions.NumberRangeException

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#99]
I have the following class:
Step to reproduce:
Just create instance of this class and call fillSampleData and save it. Then start the Rest Server.

```
public class PrimitiveArrayTypes {
    private static final byte SAMPLE_BYTE = 100;
    private static final byte SAMPLE_BYTE_2 = 127;
    private static final short SAMPLE_SHORT = 50;
    private static final short SAMPLE_SHORT_2 = 100;
    private static final int SAMPLE_INT = 5401;
    private static final int SAMPLE_INT_2 = 4401;
    private static final long SAMPLE_LONG = 1545455464654L;
    private static final long SAMPLE_LONG_2 = 25546455464654L;
    private static final float SAMPLE_FLOAT = 3.141526f;
    private static final float SAMPLE_FLOAT_2 = 2.141526f;
    private static final double SAMPLE_DOUBLE = 3.141526545;
    private static final double SAMPLE_DOUBLE_2 = 5.141526545;
    private static final char SAMPLE_CHAR = 'c';
    private static final char SAMPLE_CHAR_2 = 'x';

    private byte[] byteValues;
    private short[] shortValues;
    private int[] intValues;
    private long[] longValues;
    private float[] floatValues;
    private double[] doubleValues;
    private boolean[] booleanValues;
    private char[] charValues;
    private char[] charEmptyValues;

    public static PrimitiveArrayTypes createEmpty() {
        PrimitiveArrayTypes a = new PrimitiveArrayTypes();
        a.byteValues = new byte[1];
        a.shortValues = new short[1];
        a.intValues = new int[1];
        a.longValues = new long[1];
        a.floatValues = new float[1];
        a.doubleValues = new double[1];
        a.booleanValues = new boolean[1];
        a.charValues = new char[1];
        a.charEmptyValues = new char[0];

        return a;
    }

    public void fillSampleData() {
        byteValues = new byte[]{SAMPLE_BYTE, SAMPLE_BYTE_2};
        shortValues = new short[]{SAMPLE_SHORT, SAMPLE_SHORT_2};
        intValues = new int[]{SAMPLE_INT, SAMPLE_INT_2};
        longValues = new long[]{SAMPLE_LONG, SAMPLE_LONG_2};
        floatValues = new float[]{SAMPLE_FLOAT, SAMPLE_FLOAT_2};
        doubleValues = new double[]{SAMPLE_DOUBLE, SAMPLE_DOUBLE_2};
        booleanValues = new boolean[]{Boolean.TRUE, Boolean.FALSE};
        charValues = new char[]{SAMPLE_CHAR, SAMPLE_CHAR_2};
        charEmptyValues = new char[0];
    }
]
```

When I have tried to display this class via GUI a receive from backend this Error:
```
[qtp650827164-22] ERROR spark.http.matching.GeneralError - 
one.microstream.exceptions.NumberRangeException
	at one.microstream.math.XMath.positive(XMath.java:1391)
	at one.microstream.persistence.binary.types.Binary.validateLoadItemContentLength(Binary.java:1934)
	at one.microstream.persistence.binary.types.Binary.update_chars(Binary.java:2114)
	at one.microstream.java.lang.BinaryHandlerNativeArray_char.updateState(BinaryHandlerNativeArray_char.java:50)
	at one.microstream.java.lang.BinaryHandlerNativeArray_char.updateState(BinaryHandlerNativeArray_char.java:1)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerNativeArray.create(ViewerBinaryTypeHandlerNativeArray.java:32)
	at one.microstream.storage.restadapter.ViewerBinaryTypeHandlerNativeArray.create(ViewerBinaryTypeHandlerNativeArray.java:1)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.createBuildItem(BinaryLoader.java:196)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.internalReadBinaryEntities(BinaryLoader.java:148)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readBinaryEntities(BinaryLoader.java:136)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityDataLocal(ChunksBuffer.java:266)
	at one.microstream.persistence.binary.types.ChunksBuffer.iterateEntityData(ChunksBuffer.java:275)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.addChunks(BinaryLoader.java:788)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.readLoadOidData(BinaryLoader.java:758)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.getObject(BinaryLoader.java:823)
	at one.microstream.storage.restadapter.ViewerBinaryPersistenceManager.getStorageObject(ViewerBinaryPersistenceManager.java:216)
	at one.microstream.storage.restadapter.EmbeddedStorageRestAdapter.getStorageObject(EmbeddedStorageRestAdapter.java:56)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReference(ObjectDescription.java:190)
	at one.microstream.storage.restadapter.ObjectDescription.lambda$2(ObjectDescription.java:149)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at one.microstream.storage.restadapter.ObjectDescription.resolveReferences(ObjectDescription.java:150)
	at one.microstream.storage.restadapter.StorageRestAdapter$Default.getObject(StorageRestAdapter.java:72)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:36)
	at one.microstream.storage.restservice.sparkjava.RouteGetObject.handle(RouteGetObject.java:1)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by zdenek-jonas** [comment]
Probably same problem as https://github.com/microstream-one/microstream-private/issues/253

**Comment by fh-ms** [comment]
No, it's a different problem.

Empty arrays work on my side, what branch and module versions do you use?

**Comment by zdenek-jonas** [comment]
After rebuild works again...
